Repository GeumZzoks/universeStay, pull requests merged in 2023-11, with the labels that each got.

#1 config: mybatis-config.xml 폼 셋팅
  src/main/resources/mybatis/mybatis-config.xml
Labels: ⚙ Setting

#2 Task 91 : swagger 세팅 및 테스트용 컨트롤러 추가.
  pom.xml
  src/main/java/com/universestay/project/docs/SwaggerConfig.java
  src/main/java/com/universestay/project/docs/SwaggerTestController.java
  src/main/java/com/universestay/project/docs/SwaggerTestModel.java
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/HI.jsp
Labels: 🎸swagger

#3 test
  a.txt
Labels: 🥰 Accessibility

#8 task-195 / fix: swagger & datasource bean 생성 충돌 에러 해결
  src/main/java/com/universestay/project/docs/SwaggerConfig.java
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
Labels: 🐛 BugFix

#9 feat: task-107
  .gitignore
  src/main/webapp/resources/css/common/global.css
  src/main/webapp/resources/font/AirbnbCereal_W_Bd.otf
  src/main/webapp/resources/font/AirbnbCereal_W_Bk.otf
  src/main/webapp/resources/font/AirbnbCereal_W_Lt.otf
  src/main/webapp/resources/font/AirbnbCereal_W_Md.otf
  src/main/webapp/resources/font/AirbnbCereal_W_XBd.otf
Labels: 🎨 Html&css

#10 task-206 / structure: 공용 폴더 추가
  src/main/webapp/WEB-INF/views/common/admin/empty.txt
  src/main/webapp/WEB-INF/views/common/user/empty.txt
Labels: 🏢 Structure

#11 feat: task-205
  src/main/webapp/resources/img/logo/big_logo_color_bgd.png
  src/main/webapp/resources/img/logo/big_logo_no_bgd.png
  src/main/webapp/resources/img/logo/big_logo_white_bgd.png
  src/main/webapp/resources/img/logo/small_logo_color_bgd.png
  src/main/webapp/resources/img/logo/small_logo_no_bgd2.png
  src/main/webapp/resources/img/logo/small_logo_white_bgd.png
Labels: 🎨 Html&css

#12 feat: Logging Framework 환경 구성 및 세팅
  .gitignore
  pom.xml
  src/main/resources/console-appender.xml
  src/main/resources/file-error-appender.xml
  src/main/resources/file-info-appender.xml
  src/main/resources/file-warn-appender.xml
  src/main/resources/logback-dev.xml
  src/main/resources/logback-prod.xml
  src/main/resources/logback.xml
Labels: 🏢 Structure

#14 feat: 회원탈퇴 html/css 개발, icon 추가
  src/main/webapp/WEB-INF/views/user/withdrawal.jsp
  src/main/webapp/resources/css/user/withdrawal.css
  src/main/webapp/resources/img/logo/logo-google.png
  src/main/webapp/resources/img/logo/logo-kakao.png
  src/main/webapp/resources/img/symbol/caution.png
Labels: ✨ Feature

#15 feat: 회원탈퇴 api 개발, structure: 프로젝트 디렉토리 구조변경
  src/main/java/com/universestay/project/controller/empty.txt
  src/main/java/com/universestay/project/dao/empty.txt
  src/main/java/com/universestay/project/domain/empty.txt
  src/main/java/com/universestay/project/dto/empty.txt
  src/main/java/com/universestay/project/service/empty.txt
  src/main/java/com/universestay/project/user/controller/UserWithdrawalController.java
  src/main/java/com/universestay/project/user/dao/UserWithdrawalDao.java
  src/main/java/com/universestay/project/user/dao/UserWithdrawalDaoImpl.java
  src/main/java/com/universestay/project/user/dto/UserDto.java
  src/main/java/com/universestay/project/user/service/UserWithdrawalService.java
  src/main/java/com/universestay/project/user/service/UserWithdrawalServiceImpl.java
  src/main/resources/mybatis/mapper/user/userWithdrawalMapper.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
Labels: ✨ Feature, 🏢 Structure

#17 feat: Lombok 세팅
  pom.xml
  src/main/java/com/universestay/project/LombokTestClass.java
Labels: ✨ Feature, 🏢 Structure

#18 refactor: .gitignore 추가
  .gitignore
Labels: ⚙ Setting

#19 task-135 관리자 이벤트 페이지 JSP & CSS / Controller 추가
  src/main/java/com/universestay/project/admin/controller/EventController.java
  src/main/java/com/universestay/project/admin/controller/empty.txt
  src/main/webapp/WEB-INF/views/admin/empty.txt
  src/main/webapp/WEB-INF/views/admin/event.jsp
  src/main/webapp/WEB-INF/views/admin/eventInput.jsp
  src/main/webapp/WEB-INF/views/admin/eventList.jsp
  src/main/webapp/resources/css/common/admin/event.css
Labels: 🎨 Html&css

#21 feat: 주소, 상태코드, 숙소, 숙소 편의시설, 숙소 이미지, 숙소전망, 전망 DTO 추가
  src/main/java/com/universestay/project/dto/AddressDto.java
  src/main/java/com/universestay/project/dto/CommonStatusDto.java
  src/main/java/com/universestay/project/dto/RoomAmenityDto.java
  src/main/java/com/universestay/project/dto/RoomDto.java
  src/main/java/com/universestay/project/dto/RoomImgDto.java
  src/main/java/com/universestay/project/dto/RoomViewDto.java
  src/main/java/com/universestay/project/dto/ViewDto.java
Labels: ✨ Feature

#22 feat: Admin, Event, EventImg, Inquiry, Notice, Reply DTO 추가
  src/main/java/com/universestay/project/dto/AdminDto.java
  src/main/java/com/universestay/project/dto/EventDto.java
  src/main/java/com/universestay/project/dto/EventImgDto.java
  src/main/java/com/universestay/project/dto/InquiryDto.java
  src/main/java/com/universestay/project/dto/NoticeDto.java
  src/main/java/com/universestay/project/dto/ReplyDto.java
Labels: ✨ Feature, 📃 Docs

#23 feat: 채팅 메세지, 채팅방 Dto 추가 / 관리자 이벤트 컨트롤러 변경 / 관리자 CSS 디렉토리 변경
  src/main/java/com/universestay/project/admin/controller/EventController.java
  src/main/java/com/universestay/project/dto/ChattingMessageDto.java
  src/main/java/com/universestay/project/dto/ChattingRoomDto.java
  src/main/webapp/WEB-INF/views/admin/event.jsp
  src/main/webapp/WEB-INF/views/admin/eventInput.jsp
  src/main/webapp/WEB-INF/views/admin/eventList.jsp
  src/main/webapp/resources/css/admin/event.css
  src/main/webapp/resources/css/common/admin/event.css
Labels: ✨ Feature, 🏢 Structure

#25 design: html width 1920px > 100vw 변경
  src/main/webapp/resources/css/common/global.css
Labels: 🎨 Html&css

#26 feat: OAuth, 프로필이미지, 결제카드, 쿠폰, 룸리뷰, 유저쿠폰, 유저 Dto 추가
  src/main/java/com/universestay/project/user/dto/CardDto.java
  src/main/java/com/universestay/project/user/dto/CouponDto.java
  src/main/java/com/universestay/project/user/dto/OAuthDto.java
  src/main/java/com/universestay/project/user/dto/ProfileImgDto.java
  src/main/java/com/universestay/project/user/dto/RoomReviewDto.java
  src/main/java/com/universestay/project/user/dto/UserCouponDto.java
  src/main/java/com/universestay/project/user/dto/UserDto.java
Labels: ✨ Feature

#24 feat: Alert, AlertRule, Booking, Payment, Refund Dto 추가
  src/main/java/com/universestay/project/docs/SwaggerConfig.java
  src/main/java/com/universestay/project/dto/AlertDto.java
  src/main/java/com/universestay/project/dto/AlertRuleDto.java
  src/main/java/com/universestay/project/dto/BookingDto.java
  src/main/java/com/universestay/project/dto/PaymentDto.java
  src/main/java/com/universestay/project/dto/RefundDto.java
Labels: ✨ Feature

#28 feat: 회원가입 html, css, js
  src/main/webapp/join.jsp
  src/main/webapp/resources/css/user/join.css
  src/main/webapp/resources/js/join.js
Labels: ✨ Feature

#29 feat: 로그인 API 개발
  src/main/java/com/universestay/project/user/controller/UserLoginController.java
  src/main/java/com/universestay/project/user/controller/UserWithdrawalController.java
  src/main/java/com/universestay/project/user/dao/UserLoginDao.java
  src/main/java/com/universestay/project/user/dao/UserLoginDaoImpl.java
  src/main/java/com/universestay/project/user/dao/UserWithdrawalDao.java
  src/main/java/com/universestay/project/user/service/UserLoginService.java
  src/main/java/com/universestay/project/user/service/UserLoginServiceImpl.java
  src/main/resources/mybatis/mapper/user/userLoginMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/main/webapp/WEB-INF/views/user/loginForm.jsp
Labels: ✨ Feature, 📬 API

#30 html&css: common footer html/css 개발
  src/main/webapp/WEB-INF/views/common/footer.jsp
  src/main/webapp/WEB-INF/views/user/withdrawal.jsp
  src/main/webapp/resources/css/common/footer.css
  src/main/webapp/resources/css/user/withdrawal.css
Labels: ✨ Feature, 🎨 Html&css

#32 feat: 로그인 뷰 에러처리
  src/main/java/com/universestay/project/user/controller/UserLoginController.java
  src/main/java/com/universestay/project/user/service/UserLoginService.java
  src/main/java/com/universestay/project/user/service/UserLoginServiceImpl.java
  src/main/java/com/universestay/project/viewTest.java
  src/main/webapp/WEB-INF/views/user/loginForm.jsp
Labels: ✨ Feature

#33 feat: 관리자 페이지 로그인 [HTML, CSS]
  src/main/webapp/WEB-INF/views/admin/loginForm.jsp
  src/main/webapp/resources/css/admin/loginForm.css
  src/main/webapp/resources/css/common/global.css
Labels: 🐛 BugFix, 🎨 Html&css

#34 remove: empty.txt | test file 삭제
  src/main/java/com/universestay/project/LombokTestClass.java
  src/main/java/com/universestay/project/admin/controller/empty.txt
  src/main/java/com/universestay/project/dto/AdminDto.java
  src/main/java/com/universestay/project/filter/empty.txt
  src/main/java/com/universestay/project/viewTest.java
Labels: 🏢 Structure

#35 feat: 회원탈퇴 API 보완 (회원탈퇴 뷰의 계정삭제 버튼과 컨트롤러 연결)
  src/main/java/com/universestay/project/user/controller/UserWithdrawalController.java
  src/main/java/com/universestay/project/user/dao/UserWithdrawalDao.java
  src/main/java/com/universestay/project/user/dao/UserWithdrawalDaoImpl.java
  src/main/java/com/universestay/project/user/service/UserWithdrawalServiceImpl.java
  src/main/resources/mybatis/mapper/user/userWithdrawalMapper.xml
  src/main/webapp/WEB-INF/views/user/withdrawal.jsp
  src/test/java/com/universestay/project/user/dao/UserWithdrawalDaoImplTest.java
  src/test/java/com/universestay/project/user/service/UserWithdrawalServiceImplTest.java
Labels: ✨ Feature

#36 docs: PR, COMMIT 템플릿 추가
  .github/.gitmessage.txt
  .github/pull_request_template.md
Labels: 📃 Docs

#37 feat: 관리자 공지사항 목록, 조회, 삭제, 등록, 수정 기능 구현
  src/main/java/com/universestay/project/notice/controller/NoticeController.java
  src/main/java/com/universestay/project/notice/dao/NoticeDao.java
  src/main/java/com/universestay/project/notice/dao/NoticeDaoImpl.java
  src/main/java/com/universestay/project/notice/dto/NoticeDto.java
  src/main/java/com/universestay/project/notice/service/NoticeService.java
  src/main/java/com/universestay/project/notice/service/NoticeServiceImpl.java
  src/main/resources/mybatis/mapper/notice/noticeMapper.xml
  src/main/webapp/WEB-INF/views/notice/notice.jsp
  src/main/webapp/WEB-INF/views/notice/noticeList.jsp
  src/test/java/com/universestay/project/notice/controller/NoticeControllerTest.java
  src/test/java/com/universestay/project/notice/dao/NoticeDaoImplTest.java
  src/test/java/com/universestay/project/notice/service/NoticeServiceImplTest.java
Labels: ✨ Feature

#41 feat: [1차 개발] 관리자 계정 API 로그인 구현
  src/main/java/com/universestay/project/admin/controller/LoginController.java
  src/main/java/com/universestay/project/admin/dao/LoginAdminDao.java
  src/main/java/com/universestay/project/admin/dao/LoginAdminDaoImpl.java
  src/main/java/com/universestay/project/admin/dto/AdminDto.java
  src/main/java/com/universestay/project/admin/service/LoginAdminService.java
  src/main/java/com/universestay/project/admin/service/LoginAdminServiceImpl.java
  src/main/java/com/universestay/project/docs/SwaggerConfig.java
  src/main/java/com/universestay/project/filter/AdminFilter.java
  src/main/resources/mybatis/mapper/admin/loginMapper.xml
  src/main/resources/mybatis/mapper/empty.txt
  src/main/resources/mybatis/mybatis-config.xml
  src/main/webapp/WEB-INF/views/admin/dashboard.jsp
  src/main/webapp/WEB-INF/views/admin/empty.txt
  src/main/webapp/WEB-INF/views/admin/loginForm.jsp
  src/main/webapp/WEB-INF/views/empty.txt
  src/main/webapp/WEB-INF/views/user/empty.txt
  src/main/webapp/resources/css/admin/loginForm.css
  src/main/webapp/resources/css/empty.txt
  src/main/webapp/resources/img/empty.txt
  src/main/webapp/resources/js/empty.txt
Labels: ✨ Feature, 🎨 Html&css, 📬 API, 🏢 Structure

#43 Task 200 : nav.jsp 완성 및 main 페이지 mock data 삽입
  src/main/java/com/universestay/project/docs/SwaggerTestController.java
  src/main/webapp/WEB-INF/views/common/user/footer.jsp
  src/main/webapp/WEB-INF/views/common/user/header.jsp
  src/main/webapp/WEB-INF/views/common/user/nav.jsp
  src/main/webapp/WEB-INF/views/user/main.jsp
  src/main/webapp/WEB-INF/views/user/withdrawal.jsp
  src/main/webapp/resources/css/common/header.css
  src/main/webapp/resources/css/common/nav.css
  src/main/webapp/resources/css/user/main.css
  src/main/webapp/resources/img/mock/room-mock-img.webp
  src/main/webapp/resources/img/mock/room-mock-img2.png
  src/main/webapp/resources/img/nav-search-img/category/apartment.png
  src/main/webapp/resources/img/nav-search-img/category/camping.png
  src/main/webapp/resources/img/nav-search-img/category/condominium.png
  src/main/webapp/resources/img/nav-search-img/category/family-house.png
  src/main/webapp/resources/img/nav-search-img/category/hanok.png
  src/main/webapp/resources/img/nav-search-img/category/hostel.png
  src/main/webapp/resources/img/nav-search-img/category/hotel.png
  src/main/webapp/resources/img/nav-search-img/category/motel.png
  src/main/webapp/resources/img/nav-search-img/category/officetels.png
  src/main/webapp/resources/img/nav-search-img/category/outbuilding.png
  src/main/webapp/resources/img/nav-search-img/category/pension.png
  src/main/webapp/resources/img/nav-search-img/category/residence.png
  src/main/webapp/resources/img/nav-search-img/category/resort.png
  src/main/webapp/resources/img/nav-search-img/view/beach.png
  src/main/webapp/resources/img/nav-search-img/view/city.png
  src/main/webapp/resources/img/nav-search-img/view/garden.png
  src/main/webapp/resources/img/nav-search-img/view/golf.png
  src/main/webapp/resources/img/nav-search-img/view/harbor.png
  src/main/webapp/resources/img/nav-search-img/view/lake.png
  src/main/webapp/resources/img/nav-search-img/view/mountain.png
  src/main/webapp/resources/img/nav-search-img/view/park.png
  src/main/webapp/resources/img/nav-search-img/view/resort.png
  src/main/webapp/resources/img/nav-search-img/view/river.png
  src/main/webapp/resources/img/nav-search-img/view/sea.png
  src/main/webapp/resources/img/nav-search-img/view/swimming-pool.png
  src/main/webapp/resources/img/nav-search-img/view/valley.png
  src/main/webapp/resources/img/nav-search-img/view/yard.png
  src/main/webapp/resources/js/common/header.js
Labels: ✨ Feature, 🎨 Html&css

#44 rename: 시작 페이지 화면 main.jsp로 변경
  src/main/java/com/universestay/project/docs/SwaggerTestController.java
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/main.jsp
Labels: 🏢 Structure

#45 Task 244 : 관리자 페이지 header, navigation, footer 에 global.css 적용 및 css 수정
  src/main/webapp/WEB-INF/views/common/admin/footer.jsp
  src/main/webapp/WEB-INF/views/common/admin/header.jsp
  src/main/webapp/WEB-INF/views/common/admin/navigation.jsp
Labels: 🎨 Html&css

#50 Task 240 - 회원가입 API
  src/main/java/com/universestay/project/docs/SwaggerTestController.java
  src/main/java/com/universestay/project/user/controller/JoinController.java
  src/main/java/com/universestay/project/user/service/JoinServiceImpl.java
  src/main/webapp/WEB-INF/views/common/footer.jsp
  src/main/webapp/WEB-INF/views/common/user/header.jsp
  src/main/webapp/WEB-INF/views/common/user/nav.jsp
  src/main/webapp/WEB-INF/views/user/join.jsp
  src/main/webapp/WEB-INF/views/user/withdrawal.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/main.jsp
  src/main/webapp/resources/css/common/header.css
  src/main/webapp/resources/css/common/nav.css
  src/main/webapp/resources/css/user/main.css
  src/main/webapp/resources/img/mock/room-mock-img.webp
  src/main/webapp/resources/img/mock/room-mock-img2.png
  src/main/webapp/resources/img/nav-search-img/category/apartment.png
  src/main/webapp/resources/img/nav-search-img/category/camping.png
  src/main/webapp/resources/img/nav-search-img/category/condominium.png
  src/main/webapp/resources/img/nav-search-img/category/family-house.png
  src/main/webapp/resources/img/nav-search-img/category/hanok.png
  src/main/webapp/resources/img/nav-search-img/category/hostel.png
  src/main/webapp/resources/img/nav-search-img/category/hotel.png
  src/main/webapp/resources/img/nav-search-img/category/motel.png
  src/main/webapp/resources/img/nav-search-img/category/officetels.png
  src/main/webapp/resources/img/nav-search-img/category/outbuilding.png
  src/main/webapp/resources/img/nav-search-img/category/pension.png
  src/main/webapp/resources/img/nav-search-img/category/residence.png
  src/main/webapp/resources/img/nav-search-img/category/resort.png
  src/main/webapp/resources/img/nav-search-img/view/beach.png
  src/main/webapp/resources/img/nav-search-img/view/city.png
  src/main/webapp/resources/img/nav-search-img/view/garden.png
  src/main/webapp/resources/img/nav-search-img/view/golf.png
  src/main/webapp/resources/img/nav-search-img/view/harbor.png
  src/main/webapp/resources/img/nav-search-img/view/lake.png
  src/main/webapp/resources/img/nav-search-img/view/mountain.png
  src/main/webapp/resources/img/nav-search-img/view/park.png
  src/main/webapp/resources/img/nav-search-img/view/resort.png
  src/main/webapp/resources/img/nav-search-img/view/river.png
  src/main/webapp/resources/img/nav-search-img/view/sea.png
  src/main/webapp/resources/img/nav-search-img/view/swimming-pool.png
  src/main/webapp/resources/img/nav-search-img/view/valley.png
  src/main/webapp/resources/img/nav-search-img/view/yard.png
  src/main/webapp/resources/js/common/header.js
  src/main/webapp/resources/js/join.js
Labels: ✨ Feature

#49 Task 251
  src/main/webapp/WEB-INF/views/common/user/header.jsp
  src/main/webapp/resources/css/common/header.css
  src/main/webapp/resources/js/common/header.js
Labels: ✨ Feature

#53 Revert "Task 240 - 회원가입 API "
  src/main/java/com/universestay/project/docs/SwaggerTestController.java
  src/main/java/com/universestay/project/user/controller/JoinController.java
  src/main/java/com/universestay/project/user/service/JoinServiceImpl.java
  src/main/webapp/WEB-INF/views/common/user/footer.jsp
  src/main/webapp/WEB-INF/views/common/user/header.jsp
  src/main/webapp/WEB-INF/views/common/user/nav.jsp
  src/main/webapp/WEB-INF/views/user/join.jsp
  src/main/webapp/WEB-INF/views/user/withdrawal.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/main.jsp
  src/main/webapp/resources/css/common/header.css
  src/main/webapp/resources/css/common/nav.css
  src/main/webapp/resources/css/user/main.css
  src/main/webapp/resources/img/mock/room-mock-img.webp
  src/main/webapp/resources/img/mock/room-mock-img2.png
  src/main/webapp/resources/img/nav-search-img/category/apartment.png
  src/main/webapp/resources/img/nav-search-img/category/camping.png
  src/main/webapp/resources/img/nav-search-img/category/condominium.png
  src/main/webapp/resources/img/nav-search-img/category/family-house.png
  src/main/webapp/resources/img/nav-search-img/category/hanok.png
  src/main/webapp/resources/img/nav-search-img/category/hostel.png
  src/main/webapp/resources/img/nav-search-img/category/hotel.png
  src/main/webapp/resources/img/nav-search-img/category/motel.png
  src/main/webapp/resources/img/nav-search-img/category/officetels.png
  src/main/webapp/resources/img/nav-search-img/category/outbuilding.png
  src/main/webapp/resources/img/nav-search-img/category/pension.png
  src/main/webapp/resources/img/nav-search-img/category/residence.png
  src/main/webapp/resources/img/nav-search-img/category/resort.png
  src/main/webapp/resources/img/nav-search-img/view/beach.png
  src/main/webapp/resources/img/nav-search-img/view/city.png
  src/main/webapp/resources/img/nav-search-img/view/garden.png
  src/main/webapp/resources/img/nav-search-img/view/golf.png
  src/main/webapp/resources/img/nav-search-img/view/harbor.png
  src/main/webapp/resources/img/nav-search-img/view/lake.png
  src/main/webapp/resources/img/nav-search-img/view/mountain.png
  src/main/webapp/resources/img/nav-search-img/view/park.png
  src/main/webapp/resources/img/nav-search-img/view/resort.png
  src/main/webapp/resources/img/nav-search-img/view/river.png
  src/main/webapp/resources/img/nav-search-img/view/sea.png
  src/main/webapp/resources/img/nav-search-img/view/swimming-pool.png
  src/main/webapp/resources/img/nav-search-img/view/valley.png
  src/main/webapp/resources/img/nav-search-img/view/yard.png
  src/main/webapp/resources/js/common/header.js
  src/main/webapp/resources/js/join.js
Labels: 🐛 BugFix

#54 refactor: CSS 파일 경로 수정 및 BEM 명명규칙 적용
  src/main/webapp/WEB-INF/views/admin/loginForm.jsp
  src/main/webapp/resources/css2/screens/admin/loginForm.css
Labels: 🎨 Html&css, 🏢 Structure

#55 Task 255 : 이벤트 페이지 CSS & JSP 파일 CSS 변경
  src/main/webapp/WEB-INF/views/admin/event.jsp
  src/main/webapp/WEB-INF/views/admin/eventInput.jsp
  src/main/webapp/WEB-INF/views/admin/eventList.jsp
  src/main/webapp/WEB-INF/views/admin/eventUpdate.jsp
  src/main/webapp/resources/css/admin/event.css
Labels: 🎨 Html&css

#56 feat: 로그아웃 컨트롤러 추가, 로그인 컨트롤러 맵핑 수정
  src/main/java/com/universestay/project/user/controller/UserLoginController.java
  src/main/java/com/universestay/project/user/controller/UserLogoutController.java
  src/main/java/com/universestay/project/user/dao/UserLoginDao.java
  src/main/java/com/universestay/project/user/service/UserLoginServiceImpl.java
  src/main/webapp/WEB-INF/views/HI.jsp
  src/main/webapp/WEB-INF/views/user/loginForm.jsp
  src/test/java/com/universestay/project/user/dao/UserLoginDaoImplTest.java
Labels: ✨ Feature

#58 test: Dao, Mapper 구현, Test 코드 작성 및 테스트
  src/main/java/com/universestay/project/admin/controller/LoginController.java
  src/main/java/com/universestay/project/admin/controller/RegisterController.java
  src/main/java/com/universestay/project/admin/dao/LoginAdminDao.java
  src/main/java/com/universestay/project/admin/dao/LoginAdminDaoImpl.java
  src/main/java/com/universestay/project/admin/dao/RegisterDao.java
  src/main/java/com/universestay/project/admin/dao/RegisterDaoImpl.java
  src/main/java/com/universestay/project/admin/service/LoginAdminService.java
  src/main/java/com/universestay/project/admin/service/LoginAdminServiceImpl.java
  src/main/resources/mybatis/mapper/admin/loginMapper.xml
  src/main/resources/mybatis/mapper/admin/registerMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/test/java/com/universestay/project/admin/dao/RegisterDaoImplTest.java
Labels: ✨ Feature, ✅ Test

#60 fix: ClassNotFoundException 에러 처리
  src/main/java/com/universestay/project/common/exception/CommonException.java
  src/main/java/com/universestay/project/common/exception/StatusCode.java
Labels: 🐛 BugFix

#62 refactor: css 폴더 구조에 따른 BEM 명명 변경
  src/main/webapp/WEB-INF/views/user/withdrawal.jsp
  src/main/webapp/resources/css2/screens/user/withdrawal.css
  src/main/webapp/resources/css2/style.css
Labels: 🎨 Html&css

#61 Task 259 : css 컨벤션 수정
  src/main/webapp/WEB-INF/views/common/user/header.jsp
  src/main/webapp/WEB-INF/views/common/user/nav.jsp
  src/main/webapp/main.jsp
  src/main/webapp/resources/css/common/header_price-slider.css
  src/main/webapp/resources/css2/components/user/header.css
  src/main/webapp/resources/css2/components/user/header_price-slider.css
  src/main/webapp/resources/css2/components/user/nav.css
  src/main/webapp/resources/css2/screens/user/main.css
  src/main/webapp/resources/css2/style.css
  src/main/webapp/resources/js/common/header.js
  src/main/webapp/resources/js/common/header_slider.js
  src/main/webapp/resources/js/join.js
Labels: 🎨 Html&css

#57 feat: kakao, google oauth 회원가입 로그인 개발
  pom.xml
  src/main/java/com/universestay/project/oauth/common/MsgEntity.java
  src/main/java/com/universestay/project/oauth/controller/OauthLoginController.java
  src/main/java/com/universestay/project/oauth/dto/google/GoogleInfResponseDto.java
  src/main/java/com/universestay/project/oauth/dto/google/GoogleRequestDto.java
  src/main/java/com/universestay/project/oauth/dto/google/GoogleResponseDto.java
  src/main/java/com/universestay/project/oauth/dto/kakao/KakaoDTO.java
  src/main/java/com/universestay/project/oauth/service/GoogleLoginService.java
  src/main/java/com/universestay/project/oauth/service/KakaoLoginService.java
  src/main/java/com/universestay/project/user/controller/UserWithdrawalController.java
  src/main/java/com/universestay/project/user/service/UserLoginService.java
  src/main/java/com/universestay/project/user/service/UserLoginServiceImpl.java
  src/main/webapp/WEB-INF/views/user/join.jsp
  src/main/webapp/WEB-INF/views/user/loginForm.jsp
Labels: ✨ Feature, 📬 API

#66 comment: style.css 주석처리 해제
  src/main/webapp/resources/css2/style.css
Labels: 🎨 Html&css

#67 fix: user/loginForm 수정 oauth button에 onclick 속성 추가
  src/main/webapp/WEB-INF/views/user/loginForm.jsp
Labels: 🐛 BugFix

#69 fix: header.js 드롭다운 기능 fix
  src/main/webapp/WEB-INF/views/common/user/header.jsp
  src/main/webapp/resources/js/common/header.js
Labels: 🐛 BugFix

#72 feat: user webfilter 추가 ( 추후 urlPatterns 수정 필요)
  src/main/java/com/universestay/project/filter/UserFilter.java
Labels: ✨ Feature

#68 refactor: css 폴더 구조 변경에 대한 login.css 네이밍 재 적용
  src/main/webapp/WEB-INF/views/user/loginForm.jsp
  src/main/webapp/resources/css2/screens/user/login.css
Labels: 🎨 Html&css

#74 refactor: 이벤트 페이지 CSS BEM / CSS 수정 / 이벤트 서비스, 컨트롤러 변경
  src/main/java/com/universestay/project/admin/controller/EventController.java
  src/main/java/com/universestay/project/admin/service/EventServiceImpl.java
  src/main/webapp/WEB-INF/views/admin/event.jsp
  src/main/webapp/WEB-INF/views/admin/eventInput.jsp
  src/main/webapp/WEB-INF/views/admin/eventList.jsp
  src/main/webapp/WEB-INF/views/admin/eventUpdate.jsp
  src/main/webapp/WEB-INF/views/common/admin/footer.jsp
  src/main/webapp/WEB-INF/views/common/admin/header.jsp
  src/main/webapp/WEB-INF/views/common/admin/navigation.jsp
  src/main/webapp/resources/css/admin/event.css
  src/main/webapp/resources/css2/components/admin/footer.css
  src/main/webapp/resources/css2/components/admin/header.css
  src/main/webapp/resources/css2/components/admin/navigation.css
  src/main/webapp/resources/css2/screens/admin/event.css
Labels: 🐛 BugFix, 🎨 Html&css

#76 feat: 유저 로그인 시 최근 로그인 일자 저장을 위한 기능 추가
  src/main/java/com/universestay/project/admin/service/EventService.java
  src/main/java/com/universestay/project/user/controller/UserLoginController.java
  src/main/java/com/universestay/project/user/dao/UserLoginDao.java
  src/main/java/com/universestay/project/user/dao/UserLoginDaoImpl.java
  src/main/java/com/universestay/project/user/service/UserLoginService.java
  src/main/java/com/universestay/project/user/service/UserLoginServiceImpl.java
  src/main/resources/mybatis/mapper/user/userLoginMapper.xml
  src/main/webapp/WEB-INF/views/admin/dashboard.jsp
  src/main/webapp/resources/css2/style.css
  src/test/java/com/universestay/project/user/dao/UserLoginDaoImplTest.java
Labels: ✨ Feature

#79 rename: CouponDto 클래스 - 관리자 dto 폴더로 이동
  src/main/java/com/universestay/project/admin/dto/CouponDto.java
Labels: 🏢 Structure

#80 refactor: 관리자 - 문의사항(notice) 코드 및 폴더 구조 변경
  src/main/java/com/universestay/project/admin/controller/NoticeController.java
  src/main/java/com/universestay/project/admin/dao/NoticeDao.java
  src/main/java/com/universestay/project/admin/dao/NoticeDaoImpl.java
  src/main/java/com/universestay/project/admin/dto/NoticeDto.java
  src/main/java/com/universestay/project/admin/service/NoticeService.java
  src/main/java/com/universestay/project/admin/service/NoticeServiceImpl.java
  src/main/resources/mybatis/mapper/admin/noticeMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/main/webapp/WEB-INF/views/admin/notice.jsp
  src/main/webapp/WEB-INF/views/admin/noticeList.jsp
  src/test/java/com/universestay/project/notice/dao/NoticeDaoImplTest.java
  src/test/java/com/universestay/project/notice/service/NoticeServiceImplTest.java
Labels: 🏢 Structure

#82 fix: InquriyDto 경로 문제로 인한 톰캣 구동 에러 해결
  src/main/java/com/universestay/project/admin/dto/InquiryDto.java
  src/main/webapp/resources/css2/style.css
Labels: 🐛 BugFix

#81 feat: [1차 개발] 관리자 - 대시보드 API & VIEW
  src/main/java/com/universestay/project/admin/controller/DashBoardController.java
  src/main/java/com/universestay/project/admin/dao/DashBoardDao.java
  src/main/java/com/universestay/project/admin/dao/DashBoardDaoImpl.java
  src/main/resources/mybatis/mapper/admin/dashBoardMapper.xml
  src/main/webapp/WEB-INF/views/admin/dashboard.jsp
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#83 !HOTFIX: tomcat 기동 버그 수정 - DashBoardDaoImpl
  src/main/java/com/universestay/project/admin/dao/DashBoardDaoImpl.java
Labels: 🐛 BugFix

#84 task-115 Rename, Feat
  src/main/java/com/universestay/project/admin/controller/UserManagementController.java
  src/main/java/com/universestay/project/admin/dao/UserManagementDao.java
  src/main/java/com/universestay/project/admin/dao/UserManagementDaoImpl.java
  src/main/java/com/universestay/project/admin/service/UserManagementService.java
  src/main/java/com/universestay/project/admin/service/UserManagementServiceImpl.java
  src/main/java/com/universestay/project/common/PageHandler.java
  src/main/java/com/universestay/project/common/SearchCondition.java
  src/main/java/com/universestay/project/filter/AdminFilter.java
  src/main/resources/mybatis/mybatis-config.xml
  src/main/webapp/WEB-INF/views/admin/userInfo.jsp
  src/main/webapp/WEB-INF/views/admin/userList.jsp
  src/test/java/com/universestay/project/admin/dao/UserManagementDaoImplTest.java
Labels: ✨ Feature

#87 refactor : 관리자 이벤트 페이지 SearchCondition & PageHandler 경로 수정
  src/main/java/com/universestay/project/admin/controller/EventController.java
  src/main/java/com/universestay/project/admin/dao/EventDao.java
  src/main/java/com/universestay/project/admin/dao/EventDaoImpl.java
  src/main/java/com/universestay/project/admin/service/EventService.java
  src/main/java/com/universestay/project/admin/service/EventServiceImpl.java
Labels: 🐛 BugFix

#88 Task 303 - 회원가입 API
  src/main/java/com/universestay/project/user/service/JoinServiceImpl.java
  src/main/webapp/resources/js/join.js
Labels: 🐛 BugFix

#91 refactor: [관리자] 로그인 방식 변경, 닉네임 -> 이메일 방식
  src/main/java/com/universestay/project/admin/controller/LoginController.java
  src/main/java/com/universestay/project/admin/dao/LoginAdminDao.java
  src/main/java/com/universestay/project/admin/dao/LoginAdminDaoImpl.java
  src/main/java/com/universestay/project/admin/service/LoginAdminService.java
  src/main/java/com/universestay/project/admin/service/LoginAdminServiceImpl.java
  src/main/java/com/universestay/project/filter/AdminFilter.java
  src/main/resources/mybatis/mapper/admin/loginMapper.xml
  src/main/webapp/WEB-INF/views/admin/loginForm.jsp
Labels: 🐛 BugFix, 📬 API
