Repository GeumZzoks/universeStay, pull requests merged in 2023-12, with the labels that each got.

#90 Task 304 : UserDto 변경
  src/main/java/com/universestay/project/user/dto/ProfileImgDto.java
  src/main/java/com/universestay/project/user/dto/UserDto.java
  src/main/resources/mybatis/mapper/user/userInfoMapper.xml
Labels: 🐛 BugFix, ✨ Feature

#92 feat: [관리자] 회원가입 등록 폼 HTML & CSS & JS
  src/main/webapp/WEB-INF/views/admin/register.jsp
  src/main/webapp/resources/css2/screens/admin/register.css
  src/main/webapp/resources/css2/style.css
  src/main/webapp/resources/js/admin/register.js
Labels: ✨ Feature, 🎨 Html&css

#93 Task 303 - 회원가입 API
  src/main/webapp/WEB-INF/views/user/join.jsp
  src/main/webapp/resources/js/join.js
Labels: ✨ Feature

#94 feat: 회원가입 API - 이메일 중복확인
  src/main/java/com/universestay/project/user/controller/JoinController.java
  src/main/java/com/universestay/project/user/dao/UserJoinDao.java
  src/main/java/com/universestay/project/user/dao/UserJoinDaoImpl.java
  src/main/java/com/universestay/project/user/service/JoinService.java
  src/main/java/com/universestay/project/user/service/JoinServiceImpl.java
  src/main/resources/mybatis/mapper/user/UserJoinMapper.xml
  src/main/webapp/WEB-INF/views/user/join.jsp
  src/main/webapp/resources/js/join.js
Labels: ✨ Feature

#96 Task 295
  pom.xml
  src/main/java/com/universestay/project/user/controller/UserInfoController.java
  src/main/java/com/universestay/project/user/dao/ProfileImgDao.java
  src/main/java/com/universestay/project/user/dao/ProfileImgDaoImpl.java
  src/main/java/com/universestay/project/user/dto/ProfileImgDto.java
  src/main/java/com/universestay/project/user/service/UserInfoService.java
  src/main/java/com/universestay/project/user/service/UserInfoServiceImpl.java
  src/main/resources/mybatis/mapper/user/profileImgUploadMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/admin/userInfo.jsp
  src/main/webapp/WEB-INF/views/user/myPage/userInfo.jsp
  src/test/java/com/universestay/project/user/dao/UserInfoDaoImplTest.java
Labels: 🐛 BugFix, ✨ Feature, 🎨 Html&css, 📬 API

#97 Task 130 - 관리자 공지사항 화면 구현
  src/main/java/com/universestay/project/admin/controller/NoticeController.java
  src/main/java/com/universestay/project/admin/dao/NoticeDao.java
  src/main/java/com/universestay/project/admin/dao/NoticeDaoImpl.java
  src/main/java/com/universestay/project/admin/dto/NoticeDto.java
  src/main/java/com/universestay/project/admin/dto/NoticePageHandler.java
  src/main/java/com/universestay/project/admin/service/NoticeService.java
  src/main/java/com/universestay/project/admin/service/NoticeServiceImpl.java
  src/main/resources/mybatis/mapper/admin/noticeMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/main/webapp/WEB-INF/views/admin/noticeList.jsp
  src/main/webapp/WEB-INF/views/admin/noticeList2.jsp
  src/main/webapp/WEB-INF/views/admin/noticeWrite.jsp
  src/main/webapp/resources/css2/screens/admin/notice_media.css
  src/main/webapp/resources/css2/screens/admin/notice_style.css
  src/main/webapp/resources/css2/style.css
  src/test/java/com/universestay/project/notice/controller/NoticeControllerTest.java
  src/test/java/com/universestay/project/notice/dao/NoticeDaoImplTest.java
  src/test/java/com/universestay/project/notice/service/NoticeServiceImplTest.java
Labels: ✨ Feature, 🎨 Html&css

#100 html&css: admin dashboard html&css 개발
  src/main/webapp/WEB-INF/views/admin/dashboard.jsp
  src/main/webapp/resources/css2/screens/admin/dashboard.css
  src/main/webapp/resources/css2/style.css
  src/main/webapp/resources/img/admin/body/home.png
  src/main/webapp/resources/img/admin/body/home72.png
  src/main/webapp/resources/img/admin/navigation/UNSTLogo.png
  src/main/webapp/resources/img/admin/navigation/unLogo.png
Labels: 🎨 Html&css

#104 feat: [1차 개발] 관리자 회원가입 완료
  src/main/webapp/resources/css2/style.css
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#105 HOTFIX: [2차 개발] 관리자 회원가입 HTML & CSS & JS & API
  src/main/java/com/universestay/project/admin/controller/RegisterController.java
  src/main/java/com/universestay/project/admin/dao/RegisterDao.java
  src/main/java/com/universestay/project/admin/dao/RegisterDaoImpl.java
  src/main/java/com/universestay/project/admin/service/LoginAdminServiceImpl.java
  src/main/java/com/universestay/project/admin/service/RegisterService.java
  src/main/java/com/universestay/project/admin/service/RegisterServiceImpl.java
  src/main/java/com/universestay/project/filter/AdminFilter.java
  src/main/resources/mybatis/mapper/admin/registerMapper.xml
  src/main/webapp/WEB-INF/views/admin/join.jsp
  src/main/webapp/resources/css2/screens/admin/register.css
  src/main/webapp/resources/js/admin/register.js
Labels: 🐛 BugFix, ✨ Feature, 🎨 Html&css, 📬 API

#109 Task 295
  src/main/java/com/universestay/project/filter/UserFilter.java
  src/main/java/com/universestay/project/user/controller/UserInfoController.java
  src/main/java/com/universestay/project/user/dao/ProfileImgDao.java
  src/main/java/com/universestay/project/user/dao/ProfileImgDaoImpl.java
  src/main/java/com/universestay/project/user/dao/UserInfoDao.java
  src/main/java/com/universestay/project/user/dao/UserInfoDaoImpl.java
  src/main/java/com/universestay/project/user/service/ProfileImgService.java
  src/main/java/com/universestay/project/user/service/ProfileImgServiceImpl.java
  src/main/java/com/universestay/project/user/service/UserInfoService.java
  src/main/java/com/universestay/project/user/service/UserInfoServiceImpl.java
  src/main/resources/mybatis/mapper/user/profileImgUploadMapper.xml
  src/main/resources/mybatis/mapper/user/userInfoMapper.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/user/myPage/userInfo.jsp
  src/main/webapp/resources/css2/screens/user/userInfo.css
  src/main/webapp/resources/upload-imgs/profileImg/20231204113510480_43dd6c3a-7370-4ac8-abc6-2b7c046adc45.webp
  src/main/webapp/resources/upload-imgs/profileImg/20231204122317554_free-icon-heart-1077035.png
  src/main/webapp/resources/upload-imgs/profileImg/20231204122446009_free-icon-heart-1077035.png
  src/main/webapp/resources/upload-imgs/profileImg/20231204122936787_6ac1ca189762b966922b1fa90921568c.png
  src/main/webapp/resources/upload-imgs/profileImg/20231204124615081_free-icon-heart-1077035.png
  src/main/webapp/resources/upload-imgs/profileImg/20231205100354852_free-icon-export-3024597.png
  src/main/webapp/resources/upload-imgs/profileImg/20231205101107834_free-icon-heart-1077035.png
  src/main/webapp/resources/upload-imgs/profileImg/20231205101452185_free-icon-heart-1077035.png
  src/main/webapp/resources/upload-imgs/profileImg/20231205102143555_43dd6c3a-7370-4ac8-abc6-2b7c046adc45.webp
  src/main/webapp/resources/upload-imgs/profileImg/20231205102708735_free-icon-heart-1077035.png
  src/main/webapp/resources/upload-imgs/profileImg/test3.png
Labels: ✨ Feature

#110 Task 357: 관리자 이벤트 페이지 예외처리 & 메세지 추가 / 목록, 조회 JSP 변경 / 세부 CSS 변경 / AdminFilter 수정
  src/main/java/com/universestay/project/admin/controller/EventController.java
  src/main/java/com/universestay/project/admin/dao/EventDao.java
  src/main/java/com/universestay/project/admin/dao/EventDaoImpl.java
  src/main/java/com/universestay/project/admin/service/EventService.java
  src/main/java/com/universestay/project/admin/service/EventServiceImpl.java
  src/main/java/com/universestay/project/filter/AdminFilter.java
  src/main/resources/mybatis/mapper/admin/EventMapper.xml
  src/main/webapp/WEB-INF/views/admin/event.jsp
  src/main/webapp/WEB-INF/views/admin/eventInput.jsp
  src/main/webapp/WEB-INF/views/admin/eventList.jsp
  src/main/webapp/WEB-INF/views/admin/eventUpdate.jsp
  src/main/webapp/resources/css2/screens/admin/event.css
  src/test/java/com/universestay/project/admin/dao/EventDaoImplTest.java
Labels: ✨ Feature, 🎨 Html&css

#111 html: 숙소 삭제 페이지 html 개발
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/webapp/WEB-INF/views/room/roomDelete.jsp
  src/main/webapp/resources/img/room/room.png
Labels: 🎨 Html&css

#112 css: 숙소 상세페이지 css 개발
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/admin/hostingManagement.jsp
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
  src/main/webapp/resources/css2/screens/room/roomDetail.css
  src/main/webapp/resources/css2/style.css
  src/main/webapp/resources/img/mock/profile-img.jpeg
  src/main/webapp/resources/img/mock/reviewer1.jpeg
  src/main/webapp/resources/img/mock/reviewer2.jpeg
  src/main/webapp/resources/img/mock/reviewer3.jpeg
  src/main/webapp/resources/img/mock/reviewer4.jpeg
  src/main/webapp/resources/img/mock/reviewer5.jpeg
  src/main/webapp/resources/img/mock/reviewer6.jpeg
  src/main/webapp/resources/img/mock/room1.webp
  src/main/webapp/resources/img/mock/room2.webp
  src/main/webapp/resources/img/mock/room3.webp
  src/main/webapp/resources/img/mock/room4.webp
  src/main/webapp/resources/img/mock/room5.webp
  src/main/webapp/resources/js/room/roomDetail.js
Labels: 🎨 Html&css

#113 Task 131 : 공지사항 등록 기능 & 예외 처리 추가, 공지사항 상세 페이지 목록 버튼 추가
  src/main/java/com/universestay/project/admin/controller/NoticeController.java
  src/main/java/com/universestay/project/admin/dao/NoticeDao.java
  src/main/java/com/universestay/project/admin/dao/NoticeDaoImpl.java
  src/main/java/com/universestay/project/admin/dto/NoticePageHandler.java
  src/main/java/com/universestay/project/admin/service/NoticeService.java
  src/main/java/com/universestay/project/admin/service/NoticeServiceImpl.java
  src/main/resources/mybatis/mapper/admin/noticeMapper.xml
  src/main/webapp/WEB-INF/views/admin/notice.jsp
  src/main/webapp/WEB-INF/views/admin/noticeList2.jsp
  src/main/webapp/WEB-INF/views/admin/noticeUpdate.jsp
  src/main/webapp/WEB-INF/views/admin/noticeWrite.jsp
  src/main/webapp/resources/css2/screens/admin/notice_style.css
  src/test/java/com/universestay/project/notice/dao/NoticeDaoImplTest.java
  src/test/java/com/universestay/project/notice/dto/NoticePageHandlerTest.java
  src/test/java/com/universestay/project/notice/service/NoticeServiceImplTest.java
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#114 Task 354 : [HTML/CSS] 세부 레이아웃 및 CSS 작업
  .gitignore
  src/main/webapp/WEB-INF/views/user/myPage/userInfo.jsp
  src/main/webapp/resources/css2/screens/user/userInfo.css
  src/main/webapp/resources/js/user/userInfo.js
  src/main/webapp/resources/upload-imgs/profileImg/20231205112059170_profile.png
  src/main/webapp/resources/upload-imgs/profileImg/20231205112443746_free-icon-heart-1077035.png
  src/main/webapp/resources/upload-imgs/profileImg/20231205200655791_IMG_8815.jpg
  src/main/webapp/resources/upload-imgs/profileImg/20231205201048681_KakaoTalk_Photo_2023-02-24-10-46-36.jpeg
Labels: 🎨 Html&css

#116 refactor: 관리자 dashboard.jsp - dashboard.css link 삭제
  src/main/webapp/WEB-INF/views/HI.jsp
  src/main/webapp/WEB-INF/views/admin/dashboard.jsp
Labels: 🎨 Html&css, 🏢 Structure

#118 Task 250 : AWS S3 구축 & userInfo 기능 변경
  pom.xml
  src/main/java/com/universestay/project/common/S3/AwsS3ImgUploaderService.java
  src/main/java/com/universestay/project/common/S3/S3Config.java
  src/main/java/com/universestay/project/user/service/UserInfoServiceImpl.java
  src/main/webapp/resources/upload-imgs/profileImg/20231204113510480_43dd6c3a-7370-4ac8-abc6-2b7c046adc45.webp
  src/main/webapp/resources/upload-imgs/profileImg/20231204122317554_free-icon-heart-1077035.png
  src/main/webapp/resources/upload-imgs/profileImg/20231204122446009_free-icon-heart-1077035.png
  src/main/webapp/resources/upload-imgs/profileImg/20231204122936787_6ac1ca189762b966922b1fa90921568c.png
  src/main/webapp/resources/upload-imgs/profileImg/20231204124615081_free-icon-heart-1077035.png
  src/main/webapp/resources/upload-imgs/profileImg/20231205100354852_free-icon-export-3024597.png
  src/main/webapp/resources/upload-imgs/profileImg/20231205101107834_free-icon-heart-1077035.png
  src/main/webapp/resources/upload-imgs/profileImg/20231205101452185_free-icon-heart-1077035.png
  src/main/webapp/resources/upload-imgs/profileImg/20231205102143555_43dd6c3a-7370-4ac8-abc6-2b7c046adc45.webp
  src/main/webapp/resources/upload-imgs/profileImg/20231205102708735_free-icon-heart-1077035.png
  src/main/webapp/resources/upload-imgs/profileImg/20231205112059170_profile.png
  src/main/webapp/resources/upload-imgs/profileImg/20231205112443746_free-icon-heart-1077035.png
  src/main/webapp/resources/upload-imgs/profileImg/20231205200655791_IMG_8815.jpg
  src/main/webapp/resources/upload-imgs/profileImg/20231205201048681_KakaoTalk_Photo_2023-02-24-10-46-36.jpeg
  src/main/webapp/resources/upload-imgs/profileImg/test3.png
  src/test/java/com/universestay/project/common/S3/S3ConfigTest.java
Labels: ✨ Feature, 🏢 Structure

#120 css: 숙소 상세페이지 css 개발
  src/main/webapp/WEB-INF/views/room/roomDelete.jsp
  src/main/webapp/resources/css2/screens/room/roomDelete.css
  src/main/webapp/resources/css2/style.css
  src/main/webapp/resources/img/room/icons8-circle-16-green.png
  src/main/webapp/resources/img/room/icons8-circle-16-red.png
  src/main/webapp/resources/img/room/icons8-circle-16-yellow.png
  src/main/webapp/resources/img/room/room.png
  src/main/webapp/resources/img/room/room1.png
  src/main/webapp/resources/img/room/room2.png
  src/main/webapp/resources/img/room/room3.png
  src/main/webapp/resources/img/room/top-icn1.png
  src/main/webapp/resources/img/room/top-icn2.png
  src/main/webapp/resources/img/room/top-icn3.png
Labels: 🎨 Html&css

#122 refactor: 관리자 이벤트 입력 페이지 CSS 변경
  src/main/webapp/WEB-INF/views/admin/eventInput.jsp
  src/main/webapp/WEB-INF/views/admin/eventList.jsp
  src/main/webapp/WEB-INF/views/admin/eventUpdate.jsp
  src/main/webapp/resources/css2/screens/admin/event.css
Labels: 🎨 Html&css

#125 feat: MainController 추가
  src/main/java/com/universestay/project/main/controller/MainController.java
  src/main/java/com/universestay/project/user/controller/UserLoginController.java
  src/main/java/com/universestay/project/user/service/UserLoginServiceImpl.java
Labels: ✨ Feature

#128 Task 376 : 메인화면 숙소 전체 조회 + 숙소 상세로 이동 기능
  src/main/java/com/universestay/project/main/controller/MainController.java
  src/main/java/com/universestay/project/user/controller/UserLoginController.java
  src/main/java/com/universestay/project/user/controller/UserLogoutController.java
  src/main/webapp/WEB-INF/views/main/main.jsp
  src/main/webapp/resources/css2/screens/user/main.css
  src/main/webapp/resources/js/main/main.js
Labels: ✨ Feature

#129 feat: 사용자 숙소 예약 페이지 - HTML & CSS
  src/main/java/com/universestay/project/user/controller/ReservationRoomController.java
  src/main/resources/mybatis/mapper/user/reservationRoomMapper.xml
  src/main/webapp/WEB-INF/views/common/user/header.jsp
  src/main/webapp/WEB-INF/views/user/reservation.jsp
  src/main/webapp/resources/css2/screens/room/roomReservation.css
  src/main/webapp/resources/css2/style.css
  src/main/webapp/resources/css2/variable.css
  src/main/webapp/resources/js/common/header.js
Labels: ✨ Feature, 🎨 Html&css

#130 rename: 숙소 - 예약/결제 페이지 디렉토리 경로 변경
  src/main/java/com/universestay/project/room/controller/ReservationRoomController.java
  src/main/resources/mybatis/mapper/room/reservationRoomMapper.xml
  src/main/webapp/WEB-INF/views/room/reservation.jsp
Labels: 🏢 Structure

#135 task-117 Feat: 관리자 - 문의사항 구현
  src/main/java/com/universestay/project/admin/controller/InquiryController.java
  src/main/java/com/universestay/project/admin/dao/InquiryDao.java
  src/main/java/com/universestay/project/admin/dao/InquiryDaoImpl.java
  src/main/java/com/universestay/project/admin/dao/UserManagementDao.java
  src/main/java/com/universestay/project/admin/dao/UserManagementDaoImpl.java
  src/main/java/com/universestay/project/admin/dto/InquiryDto.java
  src/main/java/com/universestay/project/admin/dto/ReplyDto.java
  src/main/java/com/universestay/project/admin/service/InquiryService.java
  src/main/java/com/universestay/project/admin/service/InquiryServiceImpl.java
  src/main/java/com/universestay/project/admin/service/UserManagementService.java
  src/main/java/com/universestay/project/filter/AdminFilter.java
  src/main/resources/mybatis/mapper/admin/inquiryMapper.xml
  src/main/resources/mybatis/mapper/admin/userManagementMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/main/webapp/WEB-INF/views/admin/inquiry.jsp
  src/main/webapp/WEB-INF/views/admin/inquiryList.jsp
  src/test/java/com/universestay/project/admin/dao/InquiryDaoImplTest.java
  src/test/java/com/universestay/project/admin/dao/UserManagementDaoImplTest.java
Labels: ✨ Feature

#137 Task 380 - 로그인, 회원수정 - 비밀번호 암호화
  src/main/java/com/universestay/project/user/service/JoinServiceImpl.java
  src/main/java/com/universestay/project/user/service/PasswordEncryption.java
  src/main/java/com/universestay/project/user/service/UserInfoServiceImpl.java
  src/main/java/com/universestay/project/user/service/UserLoginServiceImpl.java
Labels: ✨ Feature

#142 Task 408 : 메인화면 캘린더 개선 & 사진 슬라이더 추가 & 각종 버그 및 디자인 개선
  src/main/webapp/WEB-INF/views/common/user/header.jsp
  src/main/webapp/WEB-INF/views/common/user/nav.jsp
  src/main/webapp/WEB-INF/views/main/main.jsp
  src/main/webapp/resources/css2/components/user/header.css
  src/main/webapp/resources/css2/components/user/nav.css
  src/main/webapp/resources/css2/screens/user/main.css
  src/main/webapp/resources/js/user/common/header.js
Labels: 🐛 BugFix, ✨ Feature, 🎨 Html&css

#143 Task 409 : 메인화면 사진 뿌려주기 기능 추가
  src/main/java/com/universestay/project/main/controller/MainController.java
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/java/com/universestay/project/room/dao/RoomDao.java
  src/main/java/com/universestay/project/room/dao/RoomDaoImpl.java
  src/main/java/com/universestay/project/room/service/RoomService.java
  src/main/java/com/universestay/project/room/service/RoomServiceImpl.java
  src/main/java/com/universestay/project/user/controller/UserLoginController.java
  src/main/resources/mybatis/mapper/room/roomMapper.xml
  src/main/webapp/WEB-INF/views/main/main.jsp
  src/main/webapp/resources/img/room/prepaer_img.jpeg
Labels: ✨ Feature

#144 feat: 숙소 삭제 API 개발
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/java/com/universestay/project/room/dao/RoomDao.java
  src/main/java/com/universestay/project/room/dao/RoomDaoImpl.java
  src/main/java/com/universestay/project/room/dto/RoomDto.java
  src/main/java/com/universestay/project/room/service/RoomService.java
  src/main/java/com/universestay/project/room/service/RoomServiceImpl.java
  src/main/resources/mybatis/mapper/room/roomMapper.xml
  src/main/webapp/WEB-INF/views/room/management.jsp
  src/main/webapp/WEB-INF/views/room/roomDelete.jsp
  src/main/webapp/resources/css2/screens/room/roomDelete.css
  src/main/webapp/resources/css2/screens/room/roomManagement.css
  src/main/webapp/resources/css2/style.css
  src/main/webapp/resources/js/room/roomManagement.js
  src/test/java/com/universestay/project/room/dao/RoomDaoImplTest.java
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#145 refactor: roomMapper.xml 수정
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/resources/mybatis/mapper/room/roomMapper.xml
Labels: 🔧 Refactor

#146 html & css : 숙소 등록페이지 html, css, js 개발
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/webapp/WEB-INF/views/room/roomEnroll.jsp
  src/main/webapp/resources/css2/screens/room/roomEnroll.css
  src/main/webapp/resources/css2/style.css
  src/main/webapp/resources/js/room/roomEnroll.js
  src/main/webapp/resources/js/user/common/header.js
Labels: ✨ Feature, 🎨 Html&css

#147 rename: 숙소[예약/결제] 명명규칙 변경(reservation -> book)
  src/main/java/com/universestay/project/room/controller/BookingRoomController.java
  src/main/java/com/universestay/project/room/controller/ReservationRoomController.java
  src/main/webapp/WEB-INF/views/room/book.jsp
  src/main/webapp/WEB-INF/views/room/bookShare.jsp
  src/main/webapp/resources/css2/screens/room/book.css
  src/main/webapp/resources/css2/screens/room/bookShare.css
  src/main/webapp/resources/css2/style.css
Labels: 🔧 Refactor

#148 feat: 숙소 예약 내역 공유(메일 내용) 페이지(실제 메일 내용) HTML & CSS
  src/main/java/com/universestay/project/room/service/BookShareMailSendService.java
Labels: 🎨 Html&css

#149 fix&feat: 로그인 에러 수정 및 예외 처리 추가
  src/main/java/com/universestay/project/user/controller/UserLoginController.java
  src/main/java/com/universestay/project/user/service/UserLoginServiceImpl.java
  src/main/webapp/WEB-INF/views/user/loginForm.jsp
Labels: 🐛 BugFix, ✨ Feature

#151 Feat: Task 117 나의 예약내역 조회 구현
  src/main/java/com/universestay/project/filter/AdminFilter.java
  src/main/java/com/universestay/project/filter/UserFilter.java
  src/main/java/com/universestay/project/room/controller/MyBookingController.java
  src/main/java/com/universestay/project/room/dao/MyBookingDao.java
  src/main/java/com/universestay/project/room/dao/MyBookingDaoImpl.java
  src/main/java/com/universestay/project/room/service/MyBookingService.java
  src/main/java/com/universestay/project/room/service/MyBookingServiceImpl.java
  src/main/resources/mybatis/mapper/room/myBookingMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/main/webapp/WEB-INF/views/room/myBookings.jsp
Labels: ✨ Feature

#150 Task 417 - 숙소 카카오톡 공유하기
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
Labels: ✨ Feature

#153 Task 314: 유저 위시리스트 JSP & CSS 구현
  src/main/webapp/WEB-INF/views/user/myPage/wishList.jsp
  src/main/webapp/resources/css2/screens/user/wishlist.css
  src/main/webapp/resources/img/room/unwished.png
  src/main/webapp/resources/img/room/wished.png
Labels: 🎨 Html&css

#156 Refactor: 유저 위시리스트 JSP & CSS 수정
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/java/com/universestay/project/room/dao/RoomDao.java
  src/main/java/com/universestay/project/room/dao/RoomDaoImpl.java
  src/main/java/com/universestay/project/room/service/RoomService.java
  src/main/java/com/universestay/project/room/service/RoomServiceImpl.java
  src/main/resources/mybatis/mapper/room/roomMapper.xml
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
  src/main/webapp/WEB-INF/views/user/myPage/wishList.jsp
  src/main/webapp/resources/css2/screens/user/main.css
  src/main/webapp/resources/css2/screens/user/wishlist.css
Labels: 🎨 Html&css

#159 Task 420: 위시리스트 알림 팝업 모달 추가
  src/main/webapp/WEB-INF/views/main/main.jsp
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
  src/main/webapp/WEB-INF/views/user/myPage/wishList.jsp
  src/main/webapp/resources/css2/screens/user/wishlist.css
Labels: ✨ Feature, 🎨 Html&css

#160 Refactor: 위시리스트 CSS 수정 & 숙소 상세보기 모달 추가
  src/main/webapp/WEB-INF/views/main/main.jsp
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
  src/main/webapp/WEB-INF/views/user/myPage/wishList.jsp
Labels: 🎨 Html&css

#163 Feat: task-117 user - mypage - 여행 (나의 예약 내역) 및 리뷰작성 구현
  src/main/java/com/universestay/project/user/controller/MyBookingController.java
  src/main/java/com/universestay/project/user/dao/MyBookingDao.java
  src/main/java/com/universestay/project/user/dao/MyBookingDaoImpl.java
  src/main/java/com/universestay/project/user/dto/RoomReviewDto.java
  src/main/java/com/universestay/project/user/service/MyBookingService.java
  src/main/java/com/universestay/project/user/service/MyBookingServiceImpl.java
  src/main/java/com/universestay/project/user/service/UserLoginServiceImpl.java
  src/main/resources/mybatis/mapper/user/myBookingMapper.xml
  src/main/webapp/WEB-INF/views/common/user/header.jsp
  src/main/webapp/WEB-INF/views/user/myBookings.jsp
  src/main/webapp/resources/css2/style.css
  src/main/webapp/resources/img/user/star-white.svg
  src/main/webapp/resources/img/user/star-yellow.svg
Labels: ✨ Feature

#157 feat, API: 숙소 등록 API 개발
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/java/com/universestay/project/room/dao/RoomAmenityDao.java
  src/main/java/com/universestay/project/room/dao/RoomAmenityDaoImpl.java
  src/main/java/com/universestay/project/room/dao/RoomDao.java
  src/main/java/com/universestay/project/room/dao/RoomDaoImpl.java
  src/main/java/com/universestay/project/room/dao/RoomViewDao.java
  src/main/java/com/universestay/project/room/dao/RoomViewDaoImpl.java
  src/main/java/com/universestay/project/room/dto/RoomAmenityDto.java
  src/main/java/com/universestay/project/room/dto/RoomDto.java
  src/main/java/com/universestay/project/room/dto/RoomViewDto.java
  src/main/java/com/universestay/project/room/service/RoomService.java
  src/main/java/com/universestay/project/room/service/RoomServiceImpl.java
  src/main/resources/mybatis/mapper/room/roomAmenityMapper.xml
  src/main/resources/mybatis/mapper/room/roomMapper.xml
  src/main/resources/mybatis/mapper/room/roomViewMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/main/webapp/WEB-INF/views/room/roomEnroll.jsp
  src/main/webapp/WEB-INF/views/user/myPage/withdrawal.jsp
  src/main/webapp/resources/css2/screens/room/roomEnroll.css
  src/main/webapp/resources/js/room/roomEnroll.js
Labels: ✨ Feature, 📬 API

#164 Refactor: 이벤트 페이지 수정 & 메인 이벤트 페이지 추가 & 관리자 이벤트 Dao & Impl & Mapper 수정
  src/main/java/com/universestay/project/admin/controller/EventController.java
  src/main/java/com/universestay/project/admin/dao/EventDao.java
  src/main/java/com/universestay/project/admin/dao/EventDaoImpl.java
  src/main/java/com/universestay/project/admin/service/EventService.java
  src/main/java/com/universestay/project/admin/service/EventServiceImpl.java
  src/main/java/com/universestay/project/main/controller/MainController.java
  src/main/resources/mybatis/mapper/admin/EventMapper.xml
  src/main/webapp/WEB-INF/views/admin/eventInput.jsp
  src/main/webapp/WEB-INF/views/admin/eventUpdate.jsp
  src/main/webapp/WEB-INF/views/common/user/header.jsp
  src/main/webapp/WEB-INF/views/main/eventPage.jsp
  src/main/webapp/WEB-INF/views/main/main.jsp
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
  src/main/webapp/WEB-INF/views/user/myPage/wishList.jsp
Labels: ✨ Feature, 🎨 Html&css

#162 Task 370 : 모든 검색 쿼리 통합 + 무한스크롤 구현
  src/main/java/com/universestay/project/common/MainSearchCondition.java
  src/main/java/com/universestay/project/main/controller/MainController.java
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/java/com/universestay/project/room/dao/RoomDao.java
  src/main/java/com/universestay/project/room/dao/RoomDaoImpl.java
  src/main/java/com/universestay/project/room/service/RoomService.java
  src/main/java/com/universestay/project/room/service/RoomServiceImpl.java
  src/main/java/com/universestay/project/user/controller/UserLoginController.java
  src/main/resources/mybatis/mapper/room/roomMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/main/webapp/WEB-INF/views/common/user/footer.jsp
  src/main/webapp/WEB-INF/views/common/user/header.jsp
  src/main/webapp/WEB-INF/views/main/main.jsp
  src/main/webapp/resources/css2/components/user/footer.css
  src/main/webapp/resources/css2/screens/user/main.css
  src/main/webapp/resources/img/spinner/spinner.gif
  src/main/webapp/resources/js/main/main.js
  src/main/webapp/resources/js/user/common/header.js
  src/main/webapp/resources/js/user/common/nav.js
Labels: 🐛 BugFix, ✨ Feature, 🎨 Html&css, 📬 API

#165 hotfix: roomDao 사용하지 않는 메소드 삭제
  src/main/java/com/universestay/project/room/dao/RoomDao.java
Labels: 🐛 BugFix

#166 feat: 숙소 상세페이지 모달창 구현
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/java/com/universestay/project/room/dao/RoomAmenityDao.java
  src/main/java/com/universestay/project/room/dao/RoomAmenityDaoImpl.java
  src/main/java/com/universestay/project/room/dao/RoomDao.java
  src/main/java/com/universestay/project/room/dao/RoomDaoImpl.java
  src/main/java/com/universestay/project/room/service/RoomAmenityService.java
  src/main/java/com/universestay/project/room/service/RoomAmenityServiceImpl.java
  src/main/java/com/universestay/project/room/service/RoomService.java
  src/main/java/com/universestay/project/room/service/RoomServiceImpl.java
  src/main/java/com/universestay/project/user/controller/UserLoginController.java
  src/main/resources/mybatis/mapper/room/roomAmenityMapper.xml
  src/main/resources/mybatis/mapper/room/roomMapper.xml
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
  src/main/webapp/resources/css2/screens/room/roomDetail.css
  src/main/webapp/resources/js/room/roomDetail.js
Labels: ✨ Feature

#167 hotfix: 커밋 버그 해결
  src/main/java/com/universestay/project/room/dao/RoomDao.java
  src/main/java/com/universestay/project/room/dao/RoomDaoImpl.java
  src/main/java/com/universestay/project/room/service/RoomService.java
  src/main/java/com/universestay/project/room/service/RoomServiceImpl.java
  src/main/java/com/universestay/project/user/controller/UserLoginController.java
  src/main/resources/mybatis/mapper/room/roomMapper.xml
Labels: 🐛 BugFix

#168 feat: 호스트 숙소 등록 페이지 보완
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/java/com/universestay/project/user/controller/UserLoginController.java
  src/main/webapp/WEB-INF/views/room/management.jsp
  src/main/webapp/WEB-INF/views/user/loginForm.jsp
  src/main/webapp/resources/css2/screens/room/roomManagement.css
  src/main/webapp/resources/img/room/room2.png
  src/main/webapp/resources/img/room/room3.png
  src/main/webapp/resources/js/room/roomManagement.js
Labels: ✨ Feature, 🎨 Html&css

#170 Refactor: 찜하기 & 찜하기 모달 무한스크롤 적용(보완필요)
  src/main/java/com/universestay/project/user/controller/WishListController.java
  src/main/webapp/WEB-INF/views/main/main.jsp
Labels: 🎨 Html&css

#171 Task 344: 숙소 리뷰 목록 기능, 유저 나의 리뷰 목록 기능, log4jdbc 라이브러리 추가
  pom.xml
  src/main/java/com/universestay/project/review/controller/RoomReviewController.java
  src/main/java/com/universestay/project/review/dao/RoomReviewDao.java
  src/main/java/com/universestay/project/review/dao/RoomReviewDaoImpl.java
  src/main/java/com/universestay/project/review/dto/RoomReviewDto.java
  src/main/java/com/universestay/project/review/service/RoomReviewService.java
  src/main/java/com/universestay/project/review/service/RoomReviewServiceImpl.java
  src/main/resources/log4jdbc.log4j2.properties
  src/main/resources/mybatis/mapper/review/roomReviewMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/review/userReviews.jsp
  src/test/java/com/universestay/project/notice/controller/NoticeControllerTest.java
  src/test/java/com/universestay/project/notice/dao/NoticeDaoImplTest.java
  src/test/java/com/universestay/project/review/controller/RoomReviewControllerTest.java
  src/test/java/com/universestay/project/review/dao/ReviewDaoTest.java
  src/test/java/com/universestay/project/review/service/RoomReviewServiceTest.java
Labels: ⚙ Setting, ✨ Feature, 📬 API

#173 feat: 숙소/예약 페이지 통합 개발
  src/main/java/com/universestay/project/dto/BookingDto.java
  src/main/java/com/universestay/project/room/controller/BookingRoomController.java
  src/main/java/com/universestay/project/room/dao/BookDao.java
  src/main/java/com/universestay/project/room/dao/BookDaoImpl.java
  src/main/java/com/universestay/project/room/dto/SendEmailBookInfoDto.java
  src/main/java/com/universestay/project/room/service/BookService.java
  src/main/java/com/universestay/project/room/service/BookServiceImpl.java
  src/main/java/com/universestay/project/room/service/BookShareMailSendService.java
  src/main/resources/mybatis/mapper/room/bookRoomMapper.xml
  src/main/resources/mybatis/mapper/room/reservationRoomMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/main/webapp/WEB-INF/views/room/book.jsp
  src/main/webapp/WEB-INF/views/room/bookShare.jsp
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
  src/main/webapp/resources/css2/screens/room/book.css
  src/main/webapp/resources/js/room/book.js
  src/main/webapp/resources/js/room/bookingShare.js
  src/main/webapp/resources/js/room/roomDetail.js
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#169 refactor: 메인 컨트롤러 사용을 위한 일부 리턴 경로 수정
  src/main/java/com/universestay/project/main/controller/MainController.java
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/java/com/universestay/project/room/dao/RoomDao.java
  src/main/java/com/universestay/project/user/controller/UserLoginController.java
  src/main/webapp/WEB-INF/views/room/management.jsp
Labels: 🔧 Refactor

#174 feat: 숙소 등록페이지 사진등록 기능 구현
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/java/com/universestay/project/room/dao/RoomDao.java
  src/main/java/com/universestay/project/room/dao/RoomDaoImpl.java
  src/main/java/com/universestay/project/room/dto/RoomPhotoDto.java
  src/main/java/com/universestay/project/room/service/RoomService.java
  src/main/java/com/universestay/project/room/service/RoomServiceImpl.java
  src/main/resources/mybatis/mapper/room/roomMapper.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
  src/main/webapp/WEB-INF/views/room/roomEnroll.jsp
  src/main/webapp/WEB-INF/views/room/roomPhotoEnroll.jsp
  src/main/webapp/resources/css2/screens/room/roomEnroll.css
  src/main/webapp/resources/js/room/roomDetail.js
  src/main/webapp/resources/js/room/roomEnroll.js
  src/main/webapp/resources/js/room/roomPhotoEnroll.js
Labels: ✨ Feature

#175 HOTFIX: task-344 머지 중 에러로 긴급 머지
  src/main/java/com/universestay/project/filter/UserFilter.java
  src/main/java/com/universestay/project/user/controller/MyBookingController.java
  src/main/java/com/universestay/project/user/dao/MyBookingDao.java
  src/main/java/com/universestay/project/user/dao/MyBookingDaoImpl.java
  src/main/java/com/universestay/project/user/service/MyBookingService.java
  src/main/java/com/universestay/project/user/service/MyBookingServiceImpl.java
  src/test/java/com/universestay/project/review/dao/ReviewDaoTest.java
Labels: 🐛 BugFix

#176 Task 423 : 메인 검색창 검색어 유지 기능 추가 & 메인페이지 css 미디어쿼리, 스타일 수정 & 위시리스트 버그 수정
  src/main/java/com/universestay/project/main/controller/MainController.java
  src/main/webapp/WEB-INF/views/common/user/header.jsp
  src/main/webapp/WEB-INF/views/main/main.jsp
  src/main/webapp/resources/css2/components/user/header.css
  src/main/webapp/resources/css2/screens/user/main.css
  src/main/webapp/resources/js/user/common/header.js
Labels: 🐛 BugFix, ✨ Feature, 🎨 Html&css

#177 Refactor: 관리자 페이지 JSP & CSS 일괄 수정 & 관리자 이벤트 페이지 이미지 기능 추가
  src/main/java/com/universestay/project/admin/controller/EventController.java
  src/main/java/com/universestay/project/admin/controller/LoginController.java
  src/main/java/com/universestay/project/admin/dao/EventDao.java
  src/main/java/com/universestay/project/admin/dao/EventDaoImpl.java
  src/main/java/com/universestay/project/admin/dto/EventImgDto.java
  src/main/java/com/universestay/project/admin/service/EventService.java
  src/main/java/com/universestay/project/admin/service/EventServiceImpl.java
  src/main/resources/mybatis/mapper/admin/EventMapper.xml
  src/main/webapp/WEB-INF/views/admin/dashboard.jsp
  src/main/webapp/WEB-INF/views/admin/event.jsp
  src/main/webapp/WEB-INF/views/admin/eventInput.jsp
  src/main/webapp/WEB-INF/views/admin/eventUpdate.jsp
  src/main/webapp/WEB-INF/views/common/admin/header.jsp
  src/main/webapp/WEB-INF/views/common/admin/navigation.jsp
  src/main/webapp/resources/css2/components/admin/header.css
  src/main/webapp/resources/css2/screens/admin/coupon.css
  src/main/webapp/resources/css2/screens/admin/dashboard.css
  src/main/webapp/resources/css2/screens/admin/event.css
Labels: ✨ Feature, 🎨 Html&css

#178 feat: 숙소 예약 페이지 API
  src/main/java/com/universestay/project/main/controller/MainController.java
  src/main/java/com/universestay/project/room/controller/BookingRoomController.java
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/java/com/universestay/project/room/dao/BookDao.java
  src/main/java/com/universestay/project/room/dao/BookDaoImpl.java
  src/main/java/com/universestay/project/room/service/BookService.java
  src/main/java/com/universestay/project/room/service/BookServiceImpl.java
  src/main/java/com/universestay/project/room/service/RoomAmenityServiceImpl.java
  src/main/java/com/universestay/project/user/dao/MyBookingDaoImpl.java
  src/main/resources/mybatis/mapper/room/bookRoomMapper.xml
Labels: 🐛 BugFix, ✨ Feature, 🔧 Refactor

#179 refactor: 숙소 나의 예약 페이지 경로 수정(경민), 건너뛰기 버튼 수정
  src/main/java/com/universestay/project/user/controller/MyBookingController.java
  src/main/webapp/resources/js/room/bookingShare.js
Labels: 🔧 Refactor

#182 #충돌 해결
  src/main/resources/mybatis/mybatis-config.xml
Labels: ✨ Feature

#185 Refactor : 메인 이벤트 페이지 CSS 수정 / Controller 변경 / 이벤트 세부 페이지 JSP & CSS 추가
  src/main/java/com/universestay/project/main/controller/MainController.java
  src/main/java/com/universestay/project/main/controller/MainEventController.java
  src/main/resources/mybatis/mapper/admin/EventMapper.xml
  src/main/webapp/WEB-INF/views/main/eventDetail.jsp
  src/main/webapp/WEB-INF/views/main/eventPage.jsp
Labels: ✨ Feature, 🎨 Html&css

#181 인증번호 시간 및 확인
  pom.xml
  src/main/java/com/universestay/project/user/controller/JoinController.java
  src/main/java/com/universestay/project/user/service/MailSendService.java
  src/main/java/com/universestay/project/user/service/RedisUtil.java
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/user/join.jsp
  src/main/webapp/resources/css2/screens/user/join.css
  src/main/webapp/resources/js/user/join.js
Labels: ✨ Feature

#184 Task 434 : 메인화면 CSS 변경 (flex > Grid) & 무한스크롤 이슈 수정 & roomapper 수정
  src/main/resources/mybatis/mapper/room/roomMapper.xml
  src/main/webapp/WEB-INF/views/main/main.jsp
  src/main/webapp/resources/css2/screens/user/main.css
Labels: ✨ Feature, 🎨 Html&css

#186 feat: [1차 개발 진행중] 결제 API
  src/main/java/com/universestay/project/payment/controller/PaymentController.java
  src/main/java/com/universestay/project/payment/dao/PaymentDao.java
  src/main/java/com/universestay/project/payment/dao/PaymentDaoImpl.java
  src/main/java/com/universestay/project/payment/service/PaymentService.java
  src/main/java/com/universestay/project/payment/service/PaymentServiceImpl.java
  src/main/resources/mybatis/mapper/payment/paymentMapper.xml
  src/main/webapp/WEB-INF/views/payment/payment.jsp
  src/main/webapp/WEB-INF/views/user/myBookings.jsp
Labels: ✨ Feature, 📬 API

#187 feat: 결제 api 중간 개발 완료
  src/main/java/com/universestay/project/payment/controller/PaymentController.java
  src/main/webapp/WEB-INF/views/payment/payment.jsp
  src/main/webapp/WEB-INF/views/user/myBookings.jsp
  src/main/webapp/resources/js/payment/payment.js
Labels: ✨ Feature, 📬 API

#188 Task 438: 예약 결제 결과 DB 저장하는 API 추가
  src/main/java/com/universestay/project/dto/PaymentDto.java
  src/main/java/com/universestay/project/payment/controller/PaymentController.java
  src/main/java/com/universestay/project/payment/dao/PaymentDao.java
  src/main/java/com/universestay/project/payment/dao/PaymentDaoImpl.java
  src/main/java/com/universestay/project/payment/dto/PaymentDto.java
  src/main/java/com/universestay/project/payment/service/PaymentService.java
  src/main/java/com/universestay/project/payment/service/PaymentServiceImpl.java
  src/main/resources/mybatis/mapper/payment/paymentMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/main/webapp/WEB-INF/views/payment/payment.jsp
  src/main/webapp/resources/js/payment/payment.js
Labels: ✨ Feature, 📬 API

#189 feat: 예약하기 창 날짜 입력, 입원수 입력 기능 구현
  src/main/java/com/universestay/project/room/controller/BookingRoomController.java
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/java/com/universestay/project/room/dao/BookDao.java
  src/main/java/com/universestay/project/room/dao/BookDaoImpl.java
  src/main/resources/mybatis/mapper/room/bookRoomMapper.xml
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
  src/main/webapp/resources/css2/screens/room/roomDetail.css
  src/main/webapp/resources/js/room/roomDetail.js
  src/main/webapp/resources/js/room/roomEnroll.js
Labels: ✨ Feature, 🎨 Html&css

#191 Task 437: 나의 쿠폰 기능 추가 / 쿠폰 발급 기능 추가 / 이벤트 이미지 서버 업로드 추가 / 기타 JSP 추가 및 CSS 수정
  src/main/java/com/universestay/project/admin/controller/EventController.java
  src/main/java/com/universestay/project/admin/dao/CouponDao.java
  src/main/java/com/universestay/project/admin/dao/CouponDaoImpl.java
  src/main/java/com/universestay/project/admin/dao/EventDao.java
  src/main/java/com/universestay/project/admin/dao/EventDaoImpl.java
  src/main/java/com/universestay/project/admin/dto/CouponDto.java
  src/main/java/com/universestay/project/admin/service/CouponService.java
  src/main/java/com/universestay/project/admin/service/CouponServiceImpl.java
  src/main/java/com/universestay/project/admin/service/EventService.java
  src/main/java/com/universestay/project/admin/service/EventServiceImpl.java
  src/main/java/com/universestay/project/main/controller/MainEventController.java
  src/main/java/com/universestay/project/user/controller/UserCouponController.java
  src/main/java/com/universestay/project/user/dao/UserCouponDao.java
  src/main/java/com/universestay/project/user/dao/UserCouponDaoImpl.java
  src/main/java/com/universestay/project/user/service/UserCouponService.java
  src/main/java/com/universestay/project/user/service/UserCouponServiceImpl.java
  src/main/resources/mybatis/mapper/admin/EventMapper.xml
  src/main/resources/mybatis/mapper/admin/couponMapper.xml
  src/main/resources/mybatis/mapper/user/userCouponMapper.xml
  src/main/webapp/WEB-INF/views/admin/coupon.jsp
  src/main/webapp/WEB-INF/views/admin/event.jsp
  src/main/webapp/WEB-INF/views/admin/eventInput.jsp
  src/main/webapp/WEB-INF/views/admin/eventUpdate.jsp
  src/main/webapp/WEB-INF/views/common/user/header.jsp
  src/main/webapp/WEB-INF/views/main/eventDetail.jsp
  src/main/webapp/WEB-INF/views/main/eventPage.jsp
  src/main/webapp/WEB-INF/views/main/main.jsp
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
  src/main/webapp/WEB-INF/views/user/myPage/coupon.jsp
  src/main/webapp/WEB-INF/views/user/myPage/wishList.jsp
  src/main/webapp/resources/css2/screens/admin/coupon.css
  src/main/webapp/resources/css2/screens/admin/event.css
  src/main/webapp/resources/css2/screens/user/eventDetail.css
  src/main/webapp/resources/css2/screens/user/eventPage.css
  src/main/webapp/resources/css2/screens/user/myCoupon.css
  src/main/webapp/resources/css2/style.css
  src/main/webapp/resources/img/user/issue.png
Labels: ✨ Feature, 🎨 Html&css

#192 Hotfix: BookingDto 경로 변경
  src/main/java/com/universestay/project/room/controller/BookingRoomController.java
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/java/com/universestay/project/room/dao/BookDaoImpl.java
Labels: 🐛 BugFix

#193 feat: Payment 테이블 컬럼 추가 & 반영하여 코드 수정
  src/main/java/com/universestay/project/payment/dto/PaymentDto.java
  src/main/resources/mybatis/mapper/payment/paymentMapper.xml
  src/main/webapp/resources/js/payment/payment.js
Labels: ✨ Feature

#194 Task 341: 메인페이지 공지사항 목록, 상세페이지 기능 및 VIEW 구현, 숙소 리뷰 목록 기능 구현, 숙소 상세페이지 모달 VIEW 구현
  src/main/java/com/universestay/project/admin/controller/NoticeController.java
  src/main/java/com/universestay/project/admin/dao/NoticeDao.java
  src/main/java/com/universestay/project/admin/dao/NoticeDaoImpl.java
  src/main/java/com/universestay/project/admin/service/NoticeService.java
  src/main/java/com/universestay/project/admin/service/NoticeServiceImpl.java
  src/main/java/com/universestay/project/main/controller/MainNoticeController.java
  src/main/java/com/universestay/project/review/controller/RoomReviewController.java
  src/main/java/com/universestay/project/review/dao/RoomReviewDao.java
  src/main/java/com/universestay/project/review/dao/RoomReviewDaoImpl.java
  src/main/java/com/universestay/project/review/service/RoomReviewService.java
  src/main/java/com/universestay/project/review/service/RoomReviewServiceImpl.java
  src/main/resources/mybatis/mapper/admin/noticeMapper.xml
  src/main/resources/mybatis/mapper/review/roomReviewMapper.xml
  src/main/webapp/WEB-INF/views/admin/noticeWrite.jsp
  src/main/webapp/WEB-INF/views/main/noticeDetail.jsp
  src/main/webapp/WEB-INF/views/main/noticeList.jsp
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
  src/main/webapp/resources/css2/screens/room/roomDetail.css
  src/main/webapp/resources/js/room/roomDetail.js
  src/test/java/com/universestay/project/notice/dao/NoticeDaoImplTest.java
  src/test/java/com/universestay/project/notice/service/NoticeServiceImplTest.java
  src/test/java/com/universestay/project/review/dao/ReviewDaoTest.java
  src/test/java/com/universestay/project/review/service/RoomReviewServiceTest.java
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#195 hotfix: roomDetail.js 충돌 해결
  src/main/java/com/universestay/project/room/controller/BookingRoomController.java
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/java/com/universestay/project/room/dao/BookDaoImpl.java
  src/main/webapp/resources/js/room/roomDetail.js
Labels: 🐛 BugFix

#196 refactor: 결제 API conflict 해결
  pom.xml
  src/main/java/com/universestay/project/admin/dao/ReservationToEmailJobDaoImpl.java
  src/main/java/com/universestay/project/payment/controller/PaymentController.java
  src/main/java/com/universestay/project/payment/dao/PaymentDao.java
  src/main/java/com/universestay/project/payment/dao/PaymentDaoImpl.java
  src/main/java/com/universestay/project/payment/service/PaymentService.java
  src/main/java/com/universestay/project/payment/service/PaymentServiceImpl.java
  src/main/resources/mybatis/mapper/payment/paymentMapper.xml
  src/main/webapp/WEB-INF/views/payment/payment.jsp
  src/main/webapp/resources/js/payment/payment.js
Labels: ✨ Feature, 📬 API

#197 feat: 숙소 예약 결제 API(포트원 REST API)
  src/main/java/com/universestay/project/payment/controller/PaymentController.java
  src/main/java/com/universestay/project/payment/dao/PaymentDao.java
  src/main/java/com/universestay/project/payment/dao/PaymentDaoImpl.java
  src/main/java/com/universestay/project/payment/service/PaymentService.java
  src/main/java/com/universestay/project/payment/service/PaymentServiceImpl.java
  src/main/resources/mybatis/mapper/payment/paymentMapper.xml
  src/main/webapp/resources/js/payment/payment.js
Labels: ✨ Feature, 📬 API

#198 feat: 채팅 기능 구현
  pom.xml
  src/main/java/com/universestay/project/chat/config/WebSocketConfig.java
  src/main/java/com/universestay/project/chat/controller/ChattingController.java
  src/main/java/com/universestay/project/chat/controller/ChattingRoomController.java
  src/main/java/com/universestay/project/chat/dao/ChatMessageDao.java
  src/main/java/com/universestay/project/chat/dao/ChatMessageDaoImpl.java
  src/main/java/com/universestay/project/chat/dao/ChatRoomDao.java
  src/main/java/com/universestay/project/chat/dao/ChatRoomDaoImpl.java
  src/main/java/com/universestay/project/chat/service/ChatMessageService.java
  src/main/java/com/universestay/project/chat/service/ChatMessageServiceImpl.java
  src/main/java/com/universestay/project/chat/service/ChatRoomService.java
  src/main/java/com/universestay/project/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/universestay/project/dto/ChattingMessageDto.java
  src/main/java/com/universestay/project/dto/ChattingRoomDto.java
  src/main/resources/mybatis/mapper/chat/chatMessageMapper.xml
  src/main/resources/mybatis/mapper/chat/chatRoomMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/main/webapp/WEB-INF/views/chatting/chattingMessageList.jsp
  src/main/webapp/WEB-INF/views/chatting/chattingRoomList.jsp
  src/main/webapp/WEB-INF/views/chatting/contact_host.jsp
  src/main/webapp/WEB-INF/views/common/user/header.jsp
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
  src/main/webapp/resources/dist/sockjs.js
  src/main/webapp/resources/dist/sockjs.js.map
  src/main/webapp/resources/dist/sockjs.min.js
  src/main/webapp/resources/dist/sockjs.min.js.map
  src/main/webapp/resources/js/chat/chat.js
Labels: ✨ Feature

#199 hotfix: 충돌 해결 및 이미지 추가
  src/main/java/com/universestay/project/chat/controller/ChattingController.java
  src/main/java/com/universestay/project/chat/controller/ChattingRoomController.java
  src/main/webapp/resources/img/symbol/filter_km.svg
  src/main/webapp/resources/img/symbol/x_mark_km.svg
Labels: 🐛 BugFix

#201 fix: 숙소 예약 API 오류 해결
  src/main/java/com/universestay/project/room/controller/BookingRoomController.java
  src/main/java/com/universestay/project/room/service/BookServiceImpl.java
  src/main/java/com/universestay/project/user/controller/MyBookingController.java
Labels: 🐛 BugFix, 📬 API, 🔧 Refactor

#204 Task-449: header 햄버거 공지사항 버튼 수정
  src/main/webapp/WEB-INF/views/common/user/header.jsp
Labels: ✨ Feature

#200 fix: 헤더 유저 프로필 쿠키로 관리하도록 기능 변경
  src/main/java/com/universestay/project/main/controller/MainController.java
  src/main/java/com/universestay/project/user/controller/UserLoginController.java
  src/main/java/com/universestay/project/user/controller/UserLogoutController.java
  src/main/webapp/WEB-INF/views/common/user/header.jsp
Labels: 🐛 BugFix

#205 feat, fix : 숙소 상세페이지 JS 수정 및 개발
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
  src/main/webapp/resources/css2/screens/room/roomDetail.css
  src/main/webapp/resources/js/room/roomDetail.js
Labels: 🐛 BugFix, ✨ Feature

#206 fix: 회원탈퇴 JSP 텍스트 수정 - 에어비앤비 => 유니버스스테이
  src/main/resources/mybatis/mybatis-config.xml
  src/main/webapp/WEB-INF/views/common/user/footerNotFix.jsp
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
  src/main/webapp/WEB-INF/views/room/roomEnroll.jsp
  src/main/webapp/WEB-INF/views/room/roomPhotoEnroll.jsp
  src/main/webapp/WEB-INF/views/user/myPage/withdrawal.jsp
  src/main/webapp/resources/css2/components/user/footerNotFix.css
  src/main/webapp/resources/css2/screens/room/roomDetail.css
  src/main/webapp/resources/css2/screens/room/roomEnroll.css
  src/main/webapp/resources/css2/screens/user/withdrawal.css
  src/main/webapp/resources/css2/style.css
Labels: 🐛 BugFix, ✨ Feature

#207 refactor: DB - Booking 최종 결제 금액 추가(booking_total_pay_amount) / 숙소 예약 페이지 JS 추가 및 화면단 변경
  src/main/java/com/universestay/project/room/controller/BookingRoomController.java
  src/main/java/com/universestay/project/user/dto/BookingDto.java
  src/main/resources/mybatis/mapper/room/bookRoomMapper.xml
  src/main/webapp/WEB-INF/views/room/book.jsp
  src/main/webapp/resources/css2/screens/room/book.css
  src/main/webapp/resources/js/room/book.js
  src/main/webapp/resources/js/room/roomDetail.js
Labels: 🐛 BugFix, ✨ Feature, 🎨 Html&css, 📬 API

#208 fix: 숙소 등록페이지 JSP - 수정
  src/main/java/com/universestay/project/room/service/RoomAmenityServiceImpl.java
  src/main/webapp/WEB-INF/views/room/roomEnroll.jsp
  src/main/webapp/resources/css2/screens/room/roomDetail.css
  src/main/webapp/resources/css2/screens/room/roomEnroll.css
  src/main/webapp/resources/js/room/roomDetail.js
Labels: 🐛 BugFix, ✨ Feature

#211 refactor: [숙소 - 예약/결제] 메일 보내기 페이지 화면단 변경
  src/main/java/com/universestay/project/room/controller/BookingRoomController.java
  src/main/webapp/WEB-INF/views/room/bookShare.jsp
  src/main/webapp/resources/js/room/book.js
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#209 feat: 숙소 수정하기 API 보완
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/java/com/universestay/project/room/dao/RoomAmenityDao.java
  src/main/java/com/universestay/project/room/dao/RoomAmenityDaoImpl.java
  src/main/java/com/universestay/project/room/dao/RoomDao.java
  src/main/java/com/universestay/project/room/dao/RoomDaoImpl.java
  src/main/java/com/universestay/project/room/dao/RoomViewDao.java
  src/main/java/com/universestay/project/room/dao/RoomViewDaoImpl.java
  src/main/java/com/universestay/project/room/service/RoomAmenityService.java
  src/main/java/com/universestay/project/room/service/RoomAmenityServiceImpl.java
  src/main/java/com/universestay/project/room/service/RoomService.java
  src/main/java/com/universestay/project/room/service/RoomServiceImpl.java
  src/main/java/com/universestay/project/room/service/RoomViewService.java
  src/main/java/com/universestay/project/room/service/RoomViewServiceImpl.java
  src/main/resources/mybatis/mapper/room/roomAmenityMapper.xml
  src/main/resources/mybatis/mapper/room/roomMapper.xml
  src/main/resources/mybatis/mapper/room/roomViewMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/main/webapp/WEB-INF/views/common/user/header.jsp
  src/main/webapp/WEB-INF/views/room/modify.jsp
  src/main/webapp/WEB-INF/views/room/roomPhotoModify.jsp
Labels: ✨ Feature

#214 Refactor: 이벤트 페이지 & 위시리스트 & 관리자 유저정보 페이지 CSS & JSP 수정
  src/main/java/com/universestay/project/admin/controller/EventController.java
  src/main/java/com/universestay/project/admin/service/EventService.java
  src/main/java/com/universestay/project/admin/service/EventServiceImpl.java
  src/main/java/com/universestay/project/main/controller/MainEventController.java
  src/main/java/com/universestay/project/user/controller/WishListController.java
  src/main/resources/mybatis/mapper/admin/couponMapper.xml
  src/main/webapp/WEB-INF/views/admin/coupon.jsp
  src/main/webapp/WEB-INF/views/admin/event.jsp
  src/main/webapp/WEB-INF/views/admin/eventInput.jsp
  src/main/webapp/WEB-INF/views/admin/eventList.jsp
  src/main/webapp/WEB-INF/views/admin/eventUpdate.jsp
  src/main/webapp/WEB-INF/views/admin/userInfo.jsp
  src/main/webapp/WEB-INF/views/admin/userList.jsp
  src/main/webapp/WEB-INF/views/common/admin/header.jsp
  src/main/webapp/WEB-INF/views/common/user/header.jsp
  src/main/webapp/WEB-INF/views/main/eventPage.jsp
  src/main/webapp/WEB-INF/views/main/main.jsp
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
  src/main/webapp/WEB-INF/views/user/myPage/wishList.jsp
  src/main/webapp/resources/css2/screens/admin/event.css
  src/main/webapp/resources/css2/screens/user/eventDetail.css
  src/main/webapp/resources/css2/screens/user/eventPage.css
  src/main/webapp/resources/css2/screens/user/main.css
Labels: 🎨 Html&css

#213 feat: 나의 여행 목록 스타일 변경, 보여주는 정보 추가, 결제 대기 상태만 결제 버튼 보이게 기능 추가.
  src/main/resources/mybatis/mapper/user/myBookingMapper.xml
  src/main/webapp/WEB-INF/views/user/myBookings.jsp
  src/main/webapp/resources/css2/screens/user/myBookings.css
  src/main/webapp/resources/js/payment/payment.js
Labels: 🐛 BugFix, ✨ Feature, 🎨 Html&css

#215 feat: 코드 수정
  src/main/java/com/universestay/project/chat/controller/ChattingRoomController.java
  src/main/webapp/WEB-INF/views/chatting/contact_host.jsp
  src/main/webapp/WEB-INF/views/main/main.jsp
  src/main/webapp/WEB-INF/views/user/join.jsp
  src/main/webapp/resources/css2/screens/user/join.css
  src/main/webapp/resources/js/user/join.js
Labels: ✨ Feature, 🔧 Refactor

#218 hotfix: 괄호수정
  src/main/webapp/WEB-INF/views/user/join.jsp
Labels: 🐛 BugFix

#219 fix: 숙소 상세페이지 스크립트 닫기 문제 해결
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/java/com/universestay/project/user/dao/UserInfoDao.java
  src/main/java/com/universestay/project/user/dao/UserInfoDaoImpl.java
  src/main/resources/mybatis/mapper/user/userInfoMapper.xml
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
Labels: 🐛 BugFix

#221 fix: 숙소 상세페이지 예약하기 추가인원 가격 에러 해결
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
  src/main/webapp/resources/js/room/roomDetail.js
Labels: 🐛 BugFix

#220 feat: 호스트 연락할 때 예약하기 기능 추가
  src/main/webapp/WEB-INF/views/chatting/contact_host.jsp
  src/main/webapp/resources/js/chat/contact_host.js
Labels: ✨ Feature, 🔧 Refactor

#223 Task 444: 숙소 결제, 취소, 결제 완료 표시 기능 완료
  src/main/java/com/universestay/project/user/controller/MyBookingController.java
  src/main/webapp/WEB-INF/views/common/user/header.jsp
  src/main/webapp/WEB-INF/views/user/myBookings.jsp
  src/main/webapp/resources/css2/screens/user/myBookings.css
  src/main/webapp/resources/js/user/common/header.js
Labels: 🐛 BugFix, ✨ Feature, 🎨 Html&css

#222 fix: 숙소 상세페이지에서 '좋아요' 클릭, '공유하기' 클릭 안되는 버그 해결
  src/main/java/com/universestay/project/user/controller/WishListController.java
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
Labels: 🐛 BugFix

#224 feat: 채팅방 목록 최신 날짜 순으로 정렬
  src/main/resources/mybatis/mapper/chat/chatRoomMapper.xml
Labels: 🔧 Refactor

#226 feat: 숙소 예약 완료 후 메일 보내기 기능 구현 추가 / fix: 숙소 예약 페이지 - 달력에 예약된 날짜 표기안됨
  src/main/java/com/universestay/project/room/controller/BookingRoomController.java
  src/main/java/com/universestay/project/room/dto/SendEmailBookInfoDto.java
  src/main/java/com/universestay/project/room/service/BookShareMailSendService.java
  src/main/webapp/WEB-INF/views/room/book.jsp
  src/main/webapp/WEB-INF/views/room/bookShare.jsp
  src/main/webapp/resources/js/room/book.js
  src/main/webapp/resources/js/room/bookingShare.js
Labels: 🐛 BugFix, ✨ Feature, 🎨 Html&css, 📬 API, 🔧 Refactor

#227 feat: 버그 수정
  src/main/webapp/WEB-INF/views/chatting/chattingMessageList.jsp
  src/main/webapp/WEB-INF/views/chatting/contact_host.jsp
  src/main/webapp/resources/js/user/join.js
Labels: 🐛 BugFix, ✨ Feature, 🔧 Refactor

#229 Task 342: 공지사항 목록 페이징 VIEW css 기능 추가, 공지사항 상세 VIEW 수정, 숙소 리뷰 평균, 총 리뷰 개수 기능 추가 및 VIEW 수정
  src/main/java/com/universestay/project/review/dao/RoomReviewDao.java
  src/main/java/com/universestay/project/review/dao/RoomReviewDaoImpl.java
  src/main/java/com/universestay/project/review/service/RoomReviewService.java
  src/main/java/com/universestay/project/review/service/RoomReviewServiceImpl.java
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/resources/mybatis/mapper/review/roomReviewMapper.xml
  src/main/webapp/WEB-INF/views/main/noticeDetail.jsp
  src/main/webapp/WEB-INF/views/main/noticeList.jsp
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
  src/test/java/com/universestay/project/review/dao/ReviewDaoTest.java
  src/test/java/com/universestay/project/review/service/RoomReviewServiceTest.java
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#228 Task 464 : 이전 여행지 (리뷰 기능 보완)
  src/main/java/com/universestay/project/user/controller/MyBookingController.java
  src/main/java/com/universestay/project/user/dao/MyBookingDao.java
  src/main/java/com/universestay/project/user/dao/MyBookingDaoImpl.java
  src/main/java/com/universestay/project/user/service/MyBookingService.java
  src/main/java/com/universestay/project/user/service/MyBookingServiceImpl.java
  src/main/resources/mybatis/mapper/user/myBookingMapper.xml
  src/main/webapp/WEB-INF/views/user/myBookings.jsp
  src/main/webapp/resources/css2/screens/user/myBookings.css
  src/main/webapp/resources/css2/style.css
  src/main/webapp/resources/img/user/star-pink.svg
  src/main/webapp/resources/img/user/star-white.svg
Labels: 🐛 BugFix, ✨ Feature, 🎨 Html&css

#230 Task 467 : roomReviewAvg 오류 수정
  src/main/java/com/universestay/project/review/dao/RoomReviewDao.java
  src/main/java/com/universestay/project/review/dao/RoomReviewDaoImpl.java
  src/main/java/com/universestay/project/review/service/RoomReviewService.java
  src/main/java/com/universestay/project/review/service/RoomReviewServiceImpl.java
  src/main/java/com/universestay/project/room/controller/RoomController.java
Labels: 🐛 BugFix

#231 fix: 인원 수 계산 시 요금 정산 정상적으로 되도록 수정 완료 / 인원 수 조정 시 넘버링 오류 해결 / 디자인 변경
  src/main/java/com/universestay/project/room/controller/BookingRoomController.java
  src/main/webapp/WEB-INF/views/room/book.jsp
  src/main/webapp/resources/css2/screens/room/book.css
  src/main/webapp/resources/js/room/book.js
  src/main/webapp/resources/js/room/roomDetail.js
Labels: 🐛 BugFix, 🎨 Html&css, 📬 API, 🔧 Refactor

#234 Task 471: 프로필 사진 관련(프로필 이미지 세션 저장 / 유저 회원가입시 디폴트 프로필 이미지 경로 DB 생성, 프로필 이미지 크기 변경)
  src/main/java/com/universestay/project/main/controller/MainController.java
  src/main/java/com/universestay/project/user/controller/UserLoginController.java
  src/main/java/com/universestay/project/user/dao/ProfileImgDaoImpl.java
  src/main/java/com/universestay/project/user/service/JoinServiceImpl.java
  src/main/java/com/universestay/project/user/service/UserInfoServiceImpl.java
  src/main/webapp/WEB-INF/views/common/user/header.jsp
  src/main/webapp/WEB-INF/views/user/myPage/userInfo.jsp
  src/main/webapp/resources/css2/components/user/header.css
  src/main/webapp/resources/css2/components/user/header_price-slider.css
  src/main/webapp/resources/css2/style.css
  src/main/webapp/resources/img/user/default_profile_icon.png
Labels: 🐛 BugFix, ✨ Feature, 🔧 Refactor

#236 feat: 채팅 보완
  src/main/java/com/universestay/project/chat/controller/ChattingController.java
  src/main/java/com/universestay/project/chat/controller/ChattingRoomController.java
  src/main/webapp/WEB-INF/views/chatting/chattingMessageList.jsp
  src/main/webapp/WEB-INF/views/chatting/chattingRoomList.jsp
Labels: ✨ Feature, 🎨 Html&css, 🔧 Refactor

#237 feat: 호스트 연락하기 할때 로그인 안되어있을 때 로그인창으로 갔다가 다시 이전 페이지로 돌아오게 하기
  src/main/java/com/universestay/project/chat/controller/ChattingRoomController.java
  src/main/java/com/universestay/project/user/controller/UserLoginController.java
Labels: 🔧 Refactor

#238 Task 472: 호스트 예약관리 페이지 레이아웃 변경 및 bugfix
  src/main/resources/mybatis/mapper/user/hostBookingManagementMapper.xml
  src/main/webapp/WEB-INF/views/user/myPage/hostBookingManagement.jsp
  src/main/webapp/resources/img/symbol/check-square-svgrepo-com.svg
  src/main/webapp/resources/img/symbol/x-square-svgrepo-com.svg
Labels: 🐛 BugFix, 🎨 Html&css

#239 Task 468 : 리뷰 등록일 날짜 안 맞는 문제 해결, 리뷰 모달 창 css 수정, 숙소 상세 페이지 리뷰 css 수정 및 공지사항 등록 페이지 수정
  src/main/java/com/universestay/project/admin/controller/NoticeController.java
  src/main/webapp/WEB-INF/views/admin/notice.jsp
  src/main/webapp/WEB-INF/views/admin/noticeInput.jsp
  src/main/webapp/WEB-INF/views/admin/noticeList.jsp
  src/main/webapp/WEB-INF/views/admin/noticeWrite.jsp
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
  src/main/webapp/resources/css2/screens/room/roomDetail.css
Labels: ✨ Feature, 🎨 Html&css

#240 feat: 채팅할 때 전송 버튼을 마우스로 클릭해야만 전송이 됨 → 엔터로도 가능하게 하기
  src/main/webapp/WEB-INF/views/chatting/chattingMessageList.jsp
  src/main/webapp/WEB-INF/views/chatting/chattingRoomList.jsp
Labels: ✨ Feature, 🎨 Html&css, 🔧 Refactor

#241 fix: 관리자 회원가입 오류 해결(비밀번호 체크, 이메일 확인) / feat: 관리자 회원가입 - 이메일, 핸드폰 번호 입력 창 떼었을 때 사용가능한지 확인하기
  src/main/java/com/universestay/project/admin/controller/RegisterController.java
  src/main/java/com/universestay/project/admin/dao/RegisterDao.java
  src/main/java/com/universestay/project/admin/dao/RegisterDaoImpl.java
  src/main/java/com/universestay/project/admin/dto/AdminDto.java
  src/main/java/com/universestay/project/admin/service/RegisterService.java
  src/main/java/com/universestay/project/admin/service/RegisterServiceImpl.java
  src/main/resources/mybatis/mapper/admin/registerMapper.xml
  src/main/webapp/WEB-INF/views/admin/join.jsp
  src/main/webapp/WEB-INF/views/admin/register.jsp
  src/main/webapp/resources/js/admin/register.js
  src/test/java/com/universestay/project/admin/dao/RegisterDaoImplTest.java
Labels: 🐛 BugFix, ✨ Feature, 🎨 Html&css, 📬 API

#242 Task 474 : 매일 자정 예약건에서 체크아웃 날짜가 지난 예약건들은 이용 완료로 상태 변환시키기
  src/main/java/com/universestay/project/admin/service/ChangeBookingStatusJob.java
  src/main/java/com/universestay/project/common/config/QuartzConfig.java
  src/main/java/com/universestay/project/user/dao/MyBookingDao.java
  src/main/java/com/universestay/project/user/dao/MyBookingDaoImpl.java
  src/main/java/com/universestay/project/user/service/MyBookingService.java
  src/main/java/com/universestay/project/user/service/MyBookingServiceImpl.java
  src/main/resources/mybatis/mapper/user/myBookingMapper.xml
Labels: ✨ Feature

#233 Refactor: 관리자 쿠폰 생성 에러 수정 & 숙소 세부 페이지 찜하기 alert 문구 수정 / 찜하기 세부 CSS 수정
  src/main/java/com/universestay/project/admin/controller/CouponController.java
  src/main/java/com/universestay/project/admin/dto/CouponDto.java
  src/main/webapp/WEB-INF/views/admin/coupon.jsp
  src/main/webapp/WEB-INF/views/main/main.jsp
  src/main/webapp/WEB-INF/views/room/roomDetail.jsp
  src/main/webapp/resources/css2/screens/user/wishlist.css
Labels: 🐛 BugFix, 🎨 Html&css

#244 comment: 관리자 페이지 - 호스팅 페이지, 문의 사항 주석 / 불필요한 주석 삭제
  src/main/java/com/universestay/project/admin/controller/CouponController.java
  src/main/java/com/universestay/project/admin/controller/EventController.java
  src/main/java/com/universestay/project/admin/controller/InquiryController.java
  src/main/java/com/universestay/project/admin/controller/NoticeController.java
  src/main/java/com/universestay/project/admin/controller/UserManagementController.java
  src/main/java/com/universestay/project/admin/dao/EventDaoImpl.java
  src/main/java/com/universestay/project/main/controller/MainNoticeController.java
  src/main/webapp/WEB-INF/views/common/admin/navigation.jsp
Labels: 🔧 Refactor

#245 Refactor: 관리자 유저관리 CSS 수정
  src/main/webapp/WEB-INF/views/admin/userInfo.jsp
  src/main/webapp/WEB-INF/views/admin/userList.jsp
Labels: 🎨 Html&css

#246 feat: 사진 5장 반드시 등록하도록 버튼 처리
  src/main/webapp/WEB-INF/views/room/roomPhotoEnroll.jsp
  src/main/webapp/resources/css2/screens/room/roomEnroll.css
  src/main/webapp/resources/js/room/roomEnroll.js
  src/main/webapp/resources/js/room/roomPhotoEnroll.js
  src/main/webapp/resources/js/room/roomReEnroll.js
Labels: ✨ Feature

#249 Refactor: Task 475 - 호스트 예약 관리페이지 헤더를 호스트전용 헤더로 변경
  src/main/webapp/WEB-INF/views/common/user/hostHeader.jsp
  src/main/webapp/WEB-INF/views/user/myPage/hostBookingManagement.jsp
Labels: 🎨 Html&css, 🔧 Refactor

#248 feat: 숙소 상세 - header 수정
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/webapp/resources/css2/screens/user/main.css
Labels: ✨ Feature

#250 design: 숙소 예약 페이지 - 호스트 사진 크기 변경
  src/main/java/com/universestay/project/review/controller/RoomReviewController.java
  src/main/java/com/universestay/project/user/controller/WishListController.java
  src/main/java/com/universestay/project/user/dao/ProfileImgDaoImpl.java
  src/main/webapp/WEB-INF/views/room/book.jsp
Labels: 🎨 Html&css, 🔧 Refactor

#251 feat: 채팅 두번 전송 문제 해결
  src/main/webapp/WEB-INF/views/chatting/chattingMessageList.jsp
  src/main/webapp/WEB-INF/views/user/join.jsp
  src/main/webapp/resources/js/chat/chat.js
  src/main/webapp/resources/js/user/join.js
Labels: 🐛 BugFix, 🔧 Refactor

#253 Task 479 : 메인 푸터 변경 / 메인 메인사진 맨 앞에 보이도록 하기 / 리뷰 작성시 점수 반영되게 하기
  src/main/java/com/universestay/project/main/controller/MainController.java
  src/main/java/com/universestay/project/user/controller/MyBookingController.java
  src/main/java/com/universestay/project/user/dao/MyBookingDao.java
  src/main/java/com/universestay/project/user/dao/MyBookingDaoImpl.java
  src/main/java/com/universestay/project/user/service/MyBookingService.java
  src/main/java/com/universestay/project/user/service/MyBookingServiceImpl.java
  src/main/java/com/universestay/project/user/service/UserInfoServiceImpl.java
  src/main/resources/mybatis/mapper/user/myBookingMapper.xml
  src/main/webapp/WEB-INF/views/main/main.jsp
  src/main/webapp/resources/css2/components/user/footer.css
Labels: ✨ Feature, 🎨 Html&css

#254 Feat: 충돌해결
  src/main/java/com/universestay/project/admin/controller/DashBoardController.java
  src/main/java/com/universestay/project/admin/controller/InquiryController.java
  src/main/java/com/universestay/project/admin/dao/InquiryDao.java
  src/main/java/com/universestay/project/admin/dao/InquiryDaoImpl.java
  src/main/java/com/universestay/project/admin/dto/InquiryDto.java
  src/main/java/com/universestay/project/admin/service/InquiryService.java
  src/main/java/com/universestay/project/admin/service/InquiryServiceImpl.java
  src/main/java/com/universestay/project/chat/config/WebSocketConfig.java
  src/main/java/com/universestay/project/inquiry/controller/AdminInquiryController.java
  src/main/java/com/universestay/project/inquiry/controller/InquiryChattingController.java
  src/main/java/com/universestay/project/inquiry/controller/UserInquiryController.java
  src/main/java/com/universestay/project/inquiry/dao/AdminInquiryDao.java
  src/main/java/com/universestay/project/inquiry/dao/AdminInquiryDaoImpl.java
  src/main/java/com/universestay/project/inquiry/dao/UserInquiryDao.java
  src/main/java/com/universestay/project/inquiry/dao/UserInquiryDaoImpl.java
  src/main/java/com/universestay/project/inquiry/dto/InquiryChattingMessageDto.java
  src/main/java/com/universestay/project/inquiry/dto/InquiryChattingRoomDto.java
  src/main/java/com/universestay/project/inquiry/service/AdminInquiryService.java
  src/main/java/com/universestay/project/inquiry/service/AdminInquiryServiceImpl.java
  src/main/java/com/universestay/project/inquiry/service/UserInquiryService.java
  src/main/java/com/universestay/project/inquiry/service/UserInquiryServiceImpl.java
  src/main/java/com/universestay/project/user/controller/UserInquiryController.java
  src/main/resources/mybatis/mapper/admin/dashBoardMapper.xml
  src/main/resources/mybatis/mapper/admin/inquiryMapper.xml
  src/main/resources/mybatis/mapper/inquiry/AdminInquiryMapper.xml
  src/main/resources/mybatis/mapper/inquiry/UserInquiryMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/main/webapp/WEB-INF/views/common/admin/header.jsp
  src/main/webapp/WEB-INF/views/common/user/header.jsp
  src/main/webapp/WEB-INF/views/inquiry/adminInquiry.jsp
  src/main/webapp/WEB-INF/views/inquiry/oldInquiry.jsp
  src/main/webapp/WEB-INF/views/inquiry/oldInquiryList.jsp
  src/main/webapp/WEB-INF/views/inquiry/userInquiry.jsp
  src/main/webapp/resources/img/symbol/cross-svgrepo-com.svg
  src/main/webapp/resources/img/symbol/filter_km.svg
  src/main/webapp/resources/img/symbol/plus-svgrepo-com.svg
  src/test/java/com/universestay/project/admin/dao/InquiryDaoImplTest.java
Labels: ✨ Feature

#255 fix: 배포 후 oauth 로그인 에러
  src/main/java/com/universestay/project/oauth/service/GoogleLoginService.java
Labels: 🐛 BugFix

#256 feat: 회원가입(아이디>닉네임으로 변경), 메인 헤더 addEventListener > onClick으로 변경, 당신의 …
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/webapp/WEB-INF/views/common/user/header.jsp
  src/main/webapp/WEB-INF/views/main/main.jsp
  src/main/webapp/WEB-INF/views/user/join.jsp
  src/main/webapp/resources/css2/components/user/header.css
  src/main/webapp/resources/js/user/common/header.js
Labels: 🐛 BugFix, ✨ Feature

#257 hotfix: 같은 아이디에 등록한 프로필 이미지 만큼 리뷰를 불러오는 문제로 roomReviewMapper.xml 쿼리문 수정
  src/main/resources/mybatis/mapper/review/roomReviewMapper.xml
Labels: 🐛 BugFix

#258 refactor: 결제 시 UUID 오류 해결
  src/main/webapp/resources/js/payment/payment.js
Labels: 🐛 BugFix

#259 Fix: 호스트 예약 관리페이지 초기화면 가짜데이터 보이는 버그 수정
  src/main/webapp/WEB-INF/views/user/myBookings.jsp
  src/main/webapp/WEB-INF/views/user/myPage/hostBookingManagement.jsp
Labels: 🎨 Html&css

#262 feat: myBookings에서 host nickname이 예약자의 nickname으로 뜨는 문제 해결
  src/main/java/com/universestay/project/user/controller/MyBookingController.java
  src/main/resources/mybatis/mapper/user/myBookingMapper.xml
  src/main/webapp/WEB-INF/views/user/myBookings.jsp
Labels: 🐛 BugFix

#263 Refactor: 메인 이벤트 페이지 JSP & CSS 수정 / 이벤트 매퍼 수정
  src/main/java/com/universestay/project/main/controller/MainEventController.java
  src/main/resources/mybatis/mapper/admin/EventMapper.xml
  src/main/webapp/WEB-INF/views/main/eventPage.jsp
  src/main/webapp/resources/css2/screens/user/eventDetail.css
  src/main/webapp/resources/css2/screens/user/eventPage.css
Labels: 🎨 Html&css

#265 feat: 2번 채팅 막는 함수 추가 및 예약 하루전 조건 추가
  src/main/resources/mybatis/mapper/admin/reservationToEmailJobMapper.xml
  src/main/webapp/WEB-INF/views/chatting/chattingMessageList.jsp
Labels: ✨ Feature, 🔧 Refactor

#267 Task 484 : 검색 안되는 버그 수정, 리뷰 별점 절삭해서 DB저장
  src/main/java/com/universestay/project/admin/controller/EventController.java
  src/main/java/com/universestay/project/admin/service/HostingManagementServiceImpl.java
  src/main/java/com/universestay/project/filter/AdminFilter.java
  src/main/java/com/universestay/project/main/controller/MainController.java
  src/main/java/com/universestay/project/oauth/controller/OauthLoginController.java
  src/main/java/com/universestay/project/oauth/service/GoogleLoginService.java
  src/main/java/com/universestay/project/room/controller/RoomController.java
  src/main/java/com/universestay/project/user/controller/JoinController.java
  src/main/java/com/universestay/project/user/dao/UserJoinDaoImpl.java
  src/main/resources/mybatis/mapper/room/roomMapper.xml
  src/main/resources/mybatis/mapper/user/myBookingMapper.xml
  src/test/java/com/universestay/project/DBConnectionTest.java
Labels: 🐛 BugFix, ✨ Feature

#268 feat: 결제 취소/예약 취소 API 구현 / fix: 예약 취소/결제 취소 기능 구현 후, 새롭게 숙소 예약할 때 날짜 선택 에러 수정
  src/main/java/com/universestay/project/payment/controller/PaymentController.java
  src/main/java/com/universestay/project/payment/dao/PaymentDao.java
  src/main/java/com/universestay/project/payment/dao/PaymentDaoImpl.java
  src/main/java/com/universestay/project/payment/dto/RefundPayDto.java
  src/main/java/com/universestay/project/payment/service/PaymentService.java
  src/main/java/com/universestay/project/payment/service/PaymentServiceImpl.java
  src/main/java/com/universestay/project/room/dao/BookDao.java
  src/main/java/com/universestay/project/room/dao/BookDaoImpl.java
  src/main/java/com/universestay/project/room/service/BookService.java
  src/main/java/com/universestay/project/room/service/BookServiceImpl.java
  src/main/resources/mybatis/mapper/payment/paymentMapper.xml
  src/main/resources/mybatis/mapper/room/bookRoomMapper.xml
  src/main/webapp/resources/js/payment/payment.js
Labels: 🐛 BugFix, 📬 API

#269 fix: header isHost를 session으로 관리하도록 수정
  src/main/java/com/universestay/project/main/controller/MainController.java
  src/main/webapp/WEB-INF/views/common/user/header.jsp
Labels: 🐛 BugFix

#270 refactor: 결제/예약 취소 시 confirm 메소드 추가
  src/main/webapp/resources/js/payment/payment.js
Labels: 🔧 Refactor

#271 Refactor : 위시리스트 JSP 수정
  src/main/java/com/universestay/project/user/controller/WishListController.java
  src/main/webapp/WEB-INF/views/user/myPage/wishList.jsp
Labels: 🎨 Html&css

#273 Refactor: 예약 페이지에서 글씨 뭉개지는 현상 해결
  src/main/webapp/WEB-INF/views/room/bookShare.jsp
  src/main/webapp/resources/css2/screens/room/book.css
  src/main/webapp/resources/css2/screens/room/bookShare.css
Labels: 🎨 Html&css

#274 Docs: Readme 초기 커밋
  README.md
Labels: 📃 Docs

#275 fix: jquery 두번 임포트해서 캘린더 안되는 오류 수정
  src/main/webapp/WEB-INF/views/main/eventDetail.jsp
  src/main/webapp/WEB-INF/views/room/bookShare.jsp
Labels: ✨ Feature

#276 Fix: 호스트 예약 관리페이지 (hostheader.jsp) 헤더의 게스트모드로 전환 버튼 안나오는 현상 fix
  src/main/java/com/universestay/project/user/controller/HostBookingManagementController.java
  src/main/webapp/WEB-INF/views/user/myPage/hostBookingManagement.jsp
Labels: 🐛 BugFix

#283 Fix: Host - 숙소관리페이지에서 클릭 안 되는 현상
  src/main/webapp/WEB-INF/views/common/user/hostHeader.jsp
Labels: 🐛 BugFix, 🎨 Html&css

#284 Fix: Admin - 대시보드 문의사항,
  src/main/webapp/WEB-INF/views/admin/dashboard.jsp
  src/main/webapp/WEB-INF/views/room/book.jsp
  src/main/webapp/resources/css2/screens/admin/dashboard.css
Labels: 🐛 BugFix, 🎨 Html&css

#285 comment: 미완성 메뉴 주석처리
  src/main/webapp/WEB-INF/views/common/user/header.jsp
Labels: ✨ Feature, 🎨 Html&css

#286 fix: 미완성 메뉴 주석처리2
  src/main/webapp/WEB-INF/views/common/user/header.jsp
Labels: 🐛 BugFix

#287 fix: 관리자 문의사항 대시보드 기능 복구
  src/main/java/com/universestay/project/admin/controller/DashBoardController.java
  src/main/resources/mybatis/mapper/admin/dashBoardMapper.xml
Labels: 🐛 BugFix

#289 refactor: 관리자 대시보드 문의사항 복구
  src/main/webapp/WEB-INF/views/admin/dashboard.jsp
  src/main/webapp/resources/css2/screens/admin/dashboard.css
Labels: 🐛 BugFix
